### ISSUE TITLE
Custom WMS parameters not for basemap (av)

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#1000]
I have a question related to #986: why is the custom parameter behaviour only implemented for the baseLayer of a restriction on landownership (the wms defined in the `view_reference`-Table) and not also for the baseLayer (the background wms defined in the config-File). I would expect the custom parameters to be applied to all wms definitions in the application.

**Comment by jwkaltz** [comment]
The need for this "wms_url_keep_params" setting came in the context of Geoinfo, where they have a process which automatically and regularly changes the value of one of the WMS URL parameters in the database, so they want this value to take effect in the print without them needing to change the project configuration (parameter wms_url_params).
These URLs are treated differently from the URLs defined in the config file. But if the same logic should be applied to those URL as well, it could be done, I don't see any reason against it.

**Comment by peterschaer** [comment]
At the moment we don't need to implement this. Therefore I close this issue.
