### ISSUE TITLE
Geometric shift in dataset MotorwaysBuildingLines when comparing data imported into DB via pyramid_oereb vs. the Interlis files 

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb#1011]
Hi

we have seen a shift in the dataset MotorwaysBuildingLines, when comaring the data from our ÖREB DB to the Interlis files, which can be downloaded here: https://www.cadastre.ch/de/manual-oereb/topics/feature.html
The data in our DB was imported via "downalod_federal_data.sh" & "import_federal_topic" functionality from pyramid_oereb, with the https://data.geo.admin.ch/ch.astra.baulinien-nationalstrassen.oereb/data.zip defined in our configuration. 

I have done the comparison via FME, I imported the dataset directly from our ÖREB DB and also the Interlis. In the area close to Basel, a small shift can be seen, see picture attached. 

![image](https://user-images.githubusercontent.com/54711581/75757909-812ac300-5d33-11ea-8be1-ab5d8b592de6.png)

I did not check any other dataset, but I could imagine, that similar behaviour can be seen there too. 
I'm running pyramid_oereb 1.7.0 at the moment. 

I have discussed the issue already with Camp2Camp, and they have confirmed, that they can reproduce. Please find information from Camp2Camp here:
"Hallo Max,

Das Problem konnte ich auf der Dev-Umgebung im FME rekonstruieren.

Aus dem Code lese ich das die Projektion von LV03 auf LV95 mit pyreproj die wiederum die pyproj library verwendet. Aus meiner Sicht sollte dies nicht die Fehlerquelle sein.

Wenn ich mir das Import Skript an schaue gibt es zwei Optionen

--arc-max-diff (default: 0.001)
--arc-precision (default: 3)
welche man dem Skript mit geben kann. Wen ich den Code lese werden diese Parameter benutzt um die Genauigkeit zu bestimmen mit welchen die Linien abgespeichert werden. Ich habe das Skript mit unterschiedlichen Parametern ausgeführt, was jedoch nur teilweise erfolgreich war.

Bei Interesse kann ich diese Parameter noch genauer anschauen um die Parameter besser setzten zu können?"

Anything we/I can do here?
Thanks & Regards
Max

**Comment by kdeininger** [comment]
I think, I could solve the issue (PR #1012).

The problem was, that the import script expected the geometry elements to contain only one geometry and simply took the first one found. Unfortunately, the data contains geometries for both reference system, LV03 and LV95, which caused the LV03 geometries to be used. The coordinates got transformed to LV95, but not with high accuracy.

I have modified the script for geometry parsing to prefer LV95 geometries and only use LV03 as fallback.

**Comment by MaxHoeferGEOINFO** [comment]
Hi Karsten

looks good, after I imported data again, I made another comaprison in the same location. Now the geometry matches perfectly.

![image](https://user-images.githubusercontent.com/54711581/75959789-32119900-5ebf-11ea-8b07-df33341c0d52.png)


thank you for your help - do you know if and when this will be included in a release? 
Thanks a lot,
Max

**Comment by kdeininger** [comment]
After merging the pull request, the fix will be included in the next daily build and the following bug-fix release, probably 1.7.2.

**Comment by jwkaltz** [comment]
> After merging the pull request, the fix will be included in the next daily build and the following bug-fix release, probably 1.7.2.

We can do a maintenance release 1.7.2 soon, but preferably after #1010 is finalized.
