### ISSUE TITLE
Usage of the subtheme attribute in the OEREB frame model

### ISSUE THREAD

**Issue by sbuettler** [openoereb/pyramid_oereb#1039]
**Overall description of the situation in Ticino:**
The land use plans of Ticino are maintained in a unique and old fashion manner. The land use plans data corresponds 1to1 to the paper plans. For graphical reasons it is not possible to show too many information on a paper plan, so you categorize the information and split them up onto several thematic plans. This is still the case in Ticino, so we have data structured like thematic paper plans. The sum of a set of communal thematic plans, are completing together the land use plans topic of one single municipality. Each municipality in Ticino are creating their own specific set of thematic plans, which are describing the land use plan situation on their territory.

**Formal conflict with the swisstopo instructions:**
The swisstopo instructions of the static extract (version 2018) allows to sub-categorize the land use plans topic into 5 specific sub-topics using the subtheme attribute. Our concept handling the land use plans data was to use the subtheme attribute for communal specific thematic plans, filling up the names of the thematic plans into the attribute. In order to do so, we asked the swisstopo for permission, which was approved.

**Usage of the subtheme attribute in the Frame model Ticino:**
As already described above, the subtheme attribute in the public law restriction class allows creating a sub-categorization of the topic. In Ticino we have chosen to use the attribute in order to assign each public law restriction to a communal thematic plan by filling up the names of the thematic plans into the attribute.
In collaboration with Bern and Basel-Stadt, we had commissioned C2C to develop the OEREB-Server and the Print-Template, in order to group the data of an intersection with the land use plans topic by intersected subthemes and printing them out on separate pages for the static extract. In Ticino this approach has the disadvantage, that there is no overall visualization of the land use plans topic. Each communal thematic plan is visualized by a separate WMS-Layer. See the following example of Ascona, where the property **CH190285130721** intersects with 3 thematic plans (zone, traffic and landscape plan):

https://crdpp.geo.ti.ch/?center=2703321.5587118673,1113193.965036964&zoom=24&egrid=CH190285130721

**Zone plan:**
![zone plan](https://user-images.githubusercontent.com/29145003/80945393-03933a00-8dec-11ea-9ae3-094e192bb4cc.png)

**Traffic plan:**
![traffic plan](https://user-images.githubusercontent.com/29145003/80945410-0d1ca200-8dec-11ea-8945-8a112fa34c1e.png)

**Landscape plan:**
![lanscape plan](https://user-images.githubusercontent.com/29145003/80945419-1148bf80-8dec-11ea-869f-4267074d8fe6.png)

**Conclusions:**
In the case of Ascona, 3 thematic plans a composing the land use plans topic. Other municipalities are having 5 and even more thematic plans. We estimate that in Ticino there are more than 575 thematic plans for all communes, which means that we have to create circa 575 WMS-Layers to visualize all of them. The situation is even more complex, because the amount of all thematic plan is highly dynamic. Revisions of the land use plans in a municipality could lead to a new set of plans, which means that new WMS-layers have to be created or obsolete WMS-layers have to be deleted. **This is why the workaround to create separate topics for each thematic plan in the database is not an option. So we are depending on a solution, which permits a certain dynamic behaviour to be able to visualize the whole topic.**

**Comment by claeis** [comment]
https://cloud.geo.ti.ch/oereb/extract/reduced/xml/CH190285130721

**Comment by vvmruder** [comment]
I think this is solved with the new version of pyramid_oereb. Please feel free to reopen it something is pending.
