### ISSUE TITLE
False results in extract with concurrent requests

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#1068]
We observer a strange behaviour with pyramid_oereb. Take e.g. parcel A (CH594607413563) in the municipality of Steffisburg. It is a long street parcel and therefore takes quite some time to create the extract (5 to 10 seconds). If during this creation time another extract request is being executed by the application (e.g. parcel B (CH804335484602) in the municipality of Berne) and this second request is finished while the first request is still running the results for request A are distorted. In addition to the expected results we also get public law restrictions from parcel B!!!

You may reproduce this with the following links:

Parcel A (large; in Steffisburg)
https://oerebview.apps.be.ch/#!/d/CH594607413563 (ÖREB-Viewer)
https://www.oereb.apps.be.ch/extract/reduced/json/CH594607413563 (pyramid_oereb)

Parcel B (small; in Bern)
https://oerebview.apps.be.ch/#!/d/CH804335484602 (ÖREB-Viewer)
https://www.oereb.apps.be.ch/extract/reduced/json/CH804335484602 (pyramid_oereb)

If you issue Request A and shortly afterwards Request B and if Request B finishes before Request A then you will get plrs from Bern (Parcel B) in the results of Parcel A!

I allowed myself to reproduce this on the public pyramid_oereb instance of Basel-Landschaft:

Parcel A (large; in Niederdorf) https://geoview.bl.ch/oereb/?map_x=2623321.917&map_y=1250837.964&map_zoom=7&egrid=CH427759650890

Parcel B (small; in Röschenz)
https://geoview.bl.ch/oereb/?map_x=2602790.839&map_y=1252867.127&map_zoom=13&egrid=CH571279868321

If you issue Request A and shortly afterwards Request B and if Request B finishes before Request A then you will get plrs from Röschenz (Parcel B) in the results of Parcel A!

Our productive environment is at 1.7.1; Basel-Landschaft seems to be at 1.4.3 (according to the wiki); I was able to reproduce the behaviour locally on my dev machine with pyramid_oereb 1.7.6.

Are other cantons able to reproduce this? How can it be fixed?

**Comment by jwkaltz** [comment]
I will try to reproduce this next week, unfortunately I don't have time before; maybe somebody from the user group has time. Obviously this should not happen and needs thorough investigation.

**Comment by danduk82** [comment]
@peterschaer  I think this is a problem related to some global variable or objects in the code (which is a very common and easy to make mistake in python). Globals are common to all the threads within the same process in python. If your WSGI server is configured to mulithread the WSGI processes, then you might come to this issue.
A quick workaround is to configure the WSGI server to use multi-process single-thread. But this could have a HUGE impact on performance or even make your server crash if you use apache-wsgi and apache in mod_prefork mode and that the server gets a big peak of simoultaneous requests.
The clean way of fixing this is ensuring that there are no globals in code. This require a deep analysis of the code. I will take more time these next days to see this more in detail.

**Comment by danduk82** [comment]
@peterschaer  @jwkaltz ,
I really feel that this issue might be related with the `processor` global instance. See in `pyramid_oereb/__init__.py`:

```python
 82 def pyramid_oereb_processor(request):
 83     global processor
 84     if processor is None:
 85         init_processor()
 86     return processor
 87 
 88 
 89 def init_processor():
 90     global processor
 91 
```

It is difficult to test, I should write a bit of custom code to check the influence of such globals to see if I can "corrupt" a request with another one, but with a live debugger on. It might require some intensive work.

**Comment by ger-benjamin** [comment]
I can reproduce the issue on the Schwyz Oereb server. Try for instance with:
https://map.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/json/SZ0200001372/3201
https://map.geo.sz.ch/oereb/wsgi/oereb/extract/reduced/json/SZ0200001372/3202

(Good hint, on Chrome and Firefox, you can select multiple tabs by holding the ctrl key and refresh both at once with ctrl+r (or ctrl+shift+r))

I have added a second real estate in the demo data of local pyramid oereb (https://github.com/openoereb/pyramid_oereb/tree/mixed_queries_gspoe-38) but I currently can't reproduce the issue on with the dev server...

Side note: a helpfull website to compare two json: http://www.jsondiff.com/

**Comment by peterschaer** [comment]
Are there any updates on this issue?

**Comment by ger-benjamin** [comment]
Before to try to solve this complicated issue, I wanted to try to reproduce it on a pyramid_oereb on docker (like the dev server, but with real data).
I was able to do this test this morning and it happens less often but I still can have mixed queries....
So I don't understand exactly why I can't reproduce it on the dev server (perhaps that's too fast).

So now we will try to debug directly on a working project.
