### ISSUE TITLE
"full" PDF extract uses WMS SLD 

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb#1077]
Hi everyone

we want to integrate the full PDF extract for the Canton AR.
While integration, we have found out, that the full PDF extract requires an SLD from the WMS used. 
The SLD is not required when only a reduced extract is requested. 

We have an issue with the SLD, which we can not fix easily.

"LookupError: The image could not be downloaded. URL was: https://www.geoportal.ch/services/wms/ktai?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.geoportal.basiskarten_landschaftsmodelle.1492.0.hk_oereb&mapId=1492&CRS=EPSG%3A2056&WIDTH=2055&HEIGHT=1169&BBOX=2748662.0319265304%2C1243597.057142857%2C2748714.3140734695%2C1243626.750857143&SRS=EPSG%3A2056&sld=https%3A%2F%2Foereb.ai.ch%2Fktai%2Fwsgi%2Foereb%2Fsld%3Fegrid%3DCH214141597761, Response was <?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://wms.live.geoportal.ch:80/schemas/wms/1.3.0/exceptions_1_3_0.xsd">"

Is the request of the SLD for the full extract required? Or would it be possible that the full extract is implemented in the same way as the reduced? 
If yes, then I will work with camp2camp and let them make a configuration setting in pyramid_oereb which enables to not use the SLD. 

Thanks & Cheers
Max

**Comment by MaxHoeferGEOINFO** [comment]
Hello everyone

we would like to continue with this topic - and the SLD does not work for us unfortunately. 
Therefore, I would be happy if someone could reply here. If the SLD is not required in the full print, then I will let Camp2Camp implement the configuration setting.

Thanks
Max

**Comment by kdeininger** [comment]
I don't know, if you should spend much more time on this issue. As far as I know, the parameter `flavour` will be removed with the new version of the specification. This change will also remove the flavour `full` and every extract will be generated as `reduced` by default.

**Comment by jwkaltz** [comment]
> I don't know, if you should spend much more time on this issue. As far as I know, the parameter `flavour` will be removed with the new version of the specification. This change will also remove the flavour `full` and every extract will be generated as `reduced` by default.

Indeed I did hear that plan yesterday at the Oereb conference, but @MaxHoeferGEOINFO would like to activate the full extract for AI and in their infrastructure, this option would be needed.
