### ISSUE TITLE
Be able to run scripts with c2ctemplate-style yaml file

### ISSUE THREAD

**Issue by ger-benjamin** [openoereb/pyramid_oereb#1078]
We already support yaml with c2ctemplate-style (start with `vars`->`pyramid_oereb`) in the `pyramid_oereb.lib.config` but scripts don't have option to read it and always assume that the yaml file is "standard" (starts with the `pyramid-oereb` section).

That especially annoying with docker.

I'll join a PR to fix that.

Another option would be to remove completely the c2ctemplate system and use a `config.yaml.tmpl` file with substituted variables. My fix was quicker, that's why I've choose this solution.  But In my opinion, that would be better to have only one config.yaml file in all cases (at least one kind of file to read).

**Comment by jwkaltz** [comment]
We can close this, right @ger-benjamin ?

**Comment by ger-benjamin** [comment]
Yes, thanks
