### ISSUE TITLE
Intersection result changed geometry type - no implementation needed?

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#1090]
Canton AI (Geoinfo) reported a case (EGRID CH650359774159) where the following debugging output occurs in pyramid_oereb:
"Intersection result changed geometry type. Original geometry was Polygon and result is MultiLineString"

This originates here in the code: 
https://github.com/openoereb/pyramid_oereb/blob/f0e5988d89c283517b8fc54663fba700d59dfa46/pyramid_oereb/lib/records/geometry.py#L166-L173
and was first implemented here https://github.com/openoereb/pyramid_oereb/commit/6a804ff10bad4d7cfdb42b3f6f426bb64251268b . Before this implementation, this case was considered as an error, but currently it is not.

Is our project implementation correct by not handling this case explicitly, meaning, that it has no impact on the Oereb data produced? 
Is it maybe the case when it intersects exactly at the border, so this parcel is indeed not concerned?

**Comment by kdeininger** [comment]
This is just a hint for debugging. For example, if two polygons are touching each other, the intersection geometry will be the point or linestring representing the touching part. This intersection result should not be used for the OEREB extract, but might be interesting for further investigation.

**Comment by jwkaltz** [comment]
Thanks for the explanation @kdeininger !
I added this now to the concerned code part https://github.com/openoereb/pyramid_oereb/commit/61b539130a8b26a3764d23417c858499c29caf99.
