### ISSUE TITLE
Docker images move to GitHub

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#1096]
Camptocamp currently provides Docker images for pyramid_oereb on DockerHub (here:  [https://hub.docker.com/repository/docker/camptocamp/pyramid-oereb]

Because of policy changes of DockerHub, the images will no longer be published on DockerHub, but on GitHub instead. This requires changes in the project's continuous integration setup.

**Comment by ger-benjamin** [comment]
Done. The pyramid-oereb image are now published on Github Packages and still on DockerHub.

**Comment by jwkaltz** [comment]
@lopo977 @thomasmarti @svareg Are you (are any other cantons that you are aware of) using the published docker images of pyramid_oereb? Or are you building your docker images fully manually (I know that canton Zug and canton Schwyz for instance are not using the pyramid-oereb Docker images but building the images from another base, not from pyramid-oereb)
If you are using them, you should switch to using the Images now published on GitHub Packages.

**Comment by lopo977** [comment]
Dear @jwkaltz,
in Tessin we are using the base images
`camptocamp/c2cwsgiutils:3` and `camptocamp/mapfish_print:3.25.`

We don't use directly pyramid_oereb docker images, because we have a 5% of customizations.
We are building our docker images starting from source.

Will be the c2cwsgiutils and mapfish_print still available on dockerhub?
Thank you for the information.
Regards,
Luca Lopomo

**Comment by remyguillaume** [comment]
Hello @jwkaltz 

Thanks for the information.
At BS, we are at the moment not using the docker images of pyramid_oereb.

Regards,
Guillaume.

**Comment by jwkaltz** [comment]
> Will be the c2cwsgiutils and mapfish_print still available on dockerhub?

@lopo977 For now yes, but in the mid-term it might be that new images will be available on GitHub registry instead. In any case, we will continue to provide public images for these projects.

**Comment by voisardf** [comment]
hi,
we are not yet using docker for pyramid_oereb in NE - we plan to do so starting next year.

have a nice day,
François
