### ISSUE TITLE
Continuous Integration: move away from travis-ci.org

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#1103]
Currently, the continuous integration (notably, automated tests) are handled in travis-ci.org

However, in travis-ci.org, the following appears: "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information."

We need to evaluate whether travis-ci.com should be used instead, and if so, with which account, or if continuous integration should be migrated somewhere else.

**Comment by jwkaltz** [comment]
@kdeininger since oereb_client now has the CI on GitHub actions, I suppose it would be best to use this also for pyramid_oereb, what do you think?

**Comment by kdeininger** [comment]
I think GitHub Actions will fit our needs and it seems to be much faster. Migrating to GitHub Actions should not be very complicated.

**Comment by vvmruder** [comment]
Moving to github actions 👍

How do we plan the step.

**Comment by jwkaltz** [comment]
We plan to do this via maintenance budget. There should not be any side effects.
