### ISSUE TITLE
Request for optional input: Multiple Geolinks assigned to one Geometry & PLR

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb#1135]
Hi

we have the case for the canton AR, that they have mutliple geolinks assigned to one geometry and one PLR. 
Since the data model allows this, we need to implement a solution for this. 
Did anyone else have this situation?

I talked to Wolfgang from Camp2Camp and he said, that this currently can not be handled from pyramid_oereb. 

And, as always, it's of course kind of urgent. Unfortunately we found this quite late in the project. 
Any input/feedback is welcome. 

Thanks, 
Max from GEOINFO.

**Comment by MaxHoeferGEOINFO** [comment]
Closing the issue for now - The canton AR will re-think their data for this item.

**Comment by MaxHoeferGEOINFO** [comment]
The canton AR solved the assignement of geolinks and PLRs on their side.
But, now the canton SG wants to implement it. So I'm reopening this issue for discussion again. 
Thanks 
Max

**Comment by vvmruder** [comment]
Hi Max

Could you please provide more details about this problem? Maybe we can have a closer look on it together?

Cheers

**Comment by MaxHoeferGEOINFO** [comment]
Hi 
thank you for your reply - I actually missed your answer. I get so many emails from this here, which usually do not concern me, that I musst have deleted it. Sorry.
Since we are in a rush here, we will develop a solution with camp2camp in a custom code. 
The idea was, that possibly other cantons also need something like this, but this seems not to be the case. 

Closing the issue, since we do it via camp2camp
