### ISSUE TITLE
Python 3.7 and Shapely

### ISSUE THREAD

**Issue by svareg** [openoereb/pyramid_oereb#1141]
Hello,

At the moment, we are still using Shapely 1.6.4.post1.
I know this version should be soon replaced with a newer version, but today it seems that shapely version 1.6.4.post1 just does not exists for python 3.7. The only available version is the 1.6.4.post2.

Is anyone using pyramid_oereb with Python 3.7?
If yes, did you find a package "Shapely-1.6.4.post1-cp37-cp37m-manylinux1_x86_64.whl" anywhere?
Thanks !

**Comment by jwkaltz** [comment]
Hi @svareg ,
we have recently done maintenance tasks to add Python 3.7 and Python 3.8 to the continuous integration. I do know at least one productive installation which uses Python 3.7, it is running in Docker. As I understand, shapely is compiled in these environments during the build process.

**Comment by vvmruder** [comment]
I found the package [PyGEOS](https://github.com/pygeos/pygeos) which seems to offer functionality to completely replace shapely. I think this would be worth a trail. However I think this should be done only after main work in [project 1](https://github.com/openoereb/pyramid_oereb/projects/5) is done.

**Comment by jwkaltz** [comment]
Issue is deprecated; pyramid_oereb is now using Shapely 1.8.
