### ISSUE TITLE
Statistics: DB password hardwired in production.ini

### ISSUE THREAD

**Issue by lopo977** [openoereb/pyramid_oereb#1160]
Password or credentials are normally passed via environment variables. (i.e. SQL_ALCHEMY_URL / POSTGRES_SERVICE_PASS in config.yaml.mako / config.yaml)
For the 'statistics' functionality, the database instead password is hardwired in the production.ini file (see [handler_sqlalchemylogger])

Is it possible to use the environment variable also for the connection to the database for statistics? 
Thank you. 
Regards,
Luca

**Comment by jwkaltz** [comment]
@lopo977 Hi Luca, we did the implementation in #1167.
For better consistency, we plan to do similar adaptations for the other variables, so that they are also real environment variables, in a subsequent pull request.

**Comment by lopo977** [comment]
@jwkaltz Hi Wolfgang. 
Thank you for the adaptation. 
I've just seen the implementation in #1167
