### ISSUE TITLE
[DOC] Integrate new codelists

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1171]
Use/adapt/check values from [https://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte.xml](https://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte.xml) for:
- [ ] document type
- [ ] real estate type (Grundstücksart/type d'immeuble)
- [ ] legal state (Rechtsstatus/statut légal)
- [ ] glossary
- [ ] disclaimer (Haftungshinweis/résponsabilité légale)

where used in https://github.com/openoereb/pyramid_oereb/tree/master/pyramid_oereb/standard

**Comment by vvmruder** [comment]
@voisardf & @kdeininger : We need a valid idea how to integrate the data defined in the XML's for (Themen.xml)[https://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Themen.xml], (Texte.xml)[https://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte.xml], (Logos.xml)[https://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Logos.xml] and (Gesetze.xml)[https://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Gesetze.xml] into the system.

There are three questions:

1. Where do we store it?
2. How is it imported?
3. How do we handle the parts where some text needs to be replaced?

**Comment by kdeininger** [comment]
I think we need to provide a configurable solution. I like the idea of creating separate records (if missing) and sources for these elements. The default implementation could use tables in the main schema and a script (maybe ili2pg) to import the data. I think this solution would provide the best performance. Someone could also use the XML files directly by adapting the sources.

Another questions is, how to handle the laws in "Gesetze.xml". Currently, they are handled as documents in each topic. Should we store the laws in central table too? I would prefer the current solution as it might be difficult (or even impossible) to apply changes in the law references on each topic synchronously.

**Comment by voisardf** [comment]
I agree with @kdeininger. We should provide a configurable solution and I like the idea of the catalogues being loaded using il2pg.

I'm not yet sure if we should integrate the xml files in the project but it's probably handy as they are not going to change really often!

Regarding the theme-related laws I'm still weighting the pro's and con's to add ALL (federal, cantonal, communal) theme related legal bases in the main schema or if we should only store them in the theme related schema
