### ISSUE TITLE
Changes for class Document(Base)

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1176]
In the new specifications the classes DocumentBase, Document and Article are fusioned and the inheritance is dropped. 
This implies modifications on different levels:
### Standard model definitions for db:
https://github.com/openoereb/pyramid_oereb/tree/master/pyramid_oereb/standard/models
- [x] class Article to be removed (backward compatibility?)
- [x] class DocumentBase fusioned with class Document
- [x] class Document restructured
   - [x] official_titel - removed
   - [x] official_number - newly multilingual
   - [x] canton - removed (should we keep it?)
   - [x] municipality - removed for extract (usefull to keep it?)
   - [x] only_in_municipality - kind of replaces municipality for the transfer structure
   - [x] text_at_web - moved here from DocumentBase
   - [x] law_status - inherited from DocumentBase
   - [x] article_nb - new attribute for concerned articles
   - [x] index - new, integer to sort the document list
   - [x] published_until - new expiry date for temporary documents

### PLR sources definition:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/standard/sources/plr.py

### Record definition:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/sources/document.py

### Import Script:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/standard/xtf_import/document.py

### Renderer:
https://github.com/openoereb/pyramid_oereb/tree/master/pyramid_oereb/lib/renderer/extract/templates/xml

### Oereblex Adapter?
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/sources/document.py

**Comment by kdeininger** [comment]
Should we keep the three document sub-classes? Right now, this issue would result in the following classes:

```
DocumentRecord (base class)
  ﹂ LawRecord (current type: "Law"; new spec: "GesetzlicheGrundlage")
  ﹂ LegalProvisionRecord (current type: "LegalProvision"; new spec: "Rechtsvorschrift")
  ﹂ HintRecord (current type: "Hint"; new spec: "Hinweis")
```

The new specification defines only one class "Dokument" including an attribute for its type. I think, adapting this structure in our document classes would be much simpler. The result would be only one class `DocumentRecord` and we could use the official values for the document types. What do you think?

**Comment by kdeininger** [comment]
The attribute `article_numbers` already exists. I will keep this name instead of renaming it to `article_nb`.
