### ISSUE TITLE
Changes for class LegendEntry

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1180]
- [ ] other_theme - attribute abandonned

### What needs to be done:
remove all occurences of the attribute starting from the data model through the process up to the data-extract and PDF extract.

### Standard model definitions for db (standard models are created through templates!):
https://github.com/openoereb/pyramid_oereb/blob/787ce93db13fa9af2b775b9a80a7b4078fee56a3/pyramid_oereb/contrib/templates/plr_oereb.py.mako#L161-L219
https://github.com/openoereb/pyramid_oereb/blob/787ce93db13fa9af2b775b9a80a7b4078fee56a3/pyramid_oereb/standard/templates/plr_integer_primary_keys.py.mako#L262-L303

### PLR sources definition:
https://github.com/openoereb/pyramid_oereb/blob/787ce93db13fa9af2b775b9a80a7b4078fee56a3/pyramid_oereb/standard/sources/plr.py#L104

### Record definition:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/lib/records/view_service.py#L17-L59

### Import Script:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/standard/xtf_import/legend_entry.py

### Renderer:
https://github.com/openoereb/pyramid_oereb/blob/787ce93db13fa9af2b775b9a80a7b4078fee56a3/pyramid_oereb/lib/renderer/extract/templates/xml/legend_entry.xml#L22
https://github.com/openoereb/pyramid_oereb/blob/b20ebb5ab36b3aa888fbad083e6bc18fb1d04c36/pyramid_oereb/lib/renderer/extract/json_.py#L532-L563

### Tests:
https://github.com/openoereb/pyramid_oereb/blob/787ce93db13fa9af2b775b9a80a7b4078fee56a3/tests/records/test_legend_entry.py
https://github.com/openoereb/pyramid_oereb/blob/787ce93db13fa9af2b775b9a80a7b4078fee56a3/tests/xtf_import/test_legend_entry.py

**Comment by vvmruder** [comment]
Hi @michmuel

Ich habe noch die Infos ergänzt. Wenn du noch Fragen hast, kannst du dich einfach melden.
