### ISSUE TITLE
By XY (Type A)

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1189]
__GetEGRID Service:__
---

By XY (Type A)

**OLD:**

LV95
`https://example.com/oereb/getegrid/xml/?{INTEGER,INTEGER}`

*OR*

LV03
`https://example.com/oereb/getegrid/xml/?{INTEGER,INTEGER}`

`https://example.com/oereb/getegrid/xml?XY=608000,228000`

**NEW:**

LV95
`https://example.com/oereb/getegrid/xml/?{XY=FLOAT,FLOAT}`

`https://example.com/oereb/getegrid/xml?XY=2608000.123,1228000.123`

Mandatory: XY

**Comment by kdeininger** [comment]
The new parameter is called `EN`, e.g.:

`https://example.com/oereb/getegrid/xml/?EN=2608000.230,1228000.230`
