### ISSUE TITLE
GetEGRID() Service:

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1190]
GetEGRID() Service:
---
**NEW:**
for all, optional parameter GEOMETRY returning optional attribut LIMIT containing the feature geometries
Optional: GEOMETRY returning LIMIT

**Comment by jwkaltz** [comment]
@vvmruder could this be merged with #1193 ?

**Comment by vvmruder** [comment]
Yes-I'am still in phase of gathering. So I will consolidate in a next step. Probably I will merge several issues.
