### ISSUE TITLE
Update static extract for new federal specification

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1201]
The static extract is changed in some specific places. It is extended in structure and content. There are different places to take care of for this update.

### PrintProxy:
Since the print proxy consumes the data of the DataExtract it needs to be updated. This update also should contain the new translation texts provided by specification.

### Content
The new DataExtract contains most of the texts which are needed. So it is not necessary to have this in the print template any longer. Tasks are:

1. compare the texts which are provided [here](http://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte.xml)
2. remove texts from the print configs which can be found in 1
3. expect text in templates delivered by print parameter

**Thoughts on print proxy in general**
To be more independent on the vendor we should think of completely remove the print specific behavior from this project and set the dataextract itself as interface. This would mean to only have a configured URL for the print service which needs to be able to consume XML/JSON Dataextract to provide PDF. In terms of installation and lose coupling this would be a big improvement.

**Comment by voisardf** [comment]
well, the fix of the PDF extract is in the scope of the project. And yes, I did see this two problems too.
