### ISSUE TITLE
PDF: general points

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1210]
With the latest specifications the PDF format version has been updated to use the version PDF/A-2a by default. Also, the error messages to return if a PDF can not be produced have been defined.

### What needs to be done:
- [x] Set version to PDF/A-2a (or PDF/A-1 (ISO 19005-1:2005) if not possible) -_> stay at PDF/A-1, as JasperReports support this standard only_
- [ ] If a data set is not available due to a server or a service failure, a predefined message (multilingual) has to be returned:
DE: «Ein oder mehrere ÖREB-Themen stehen momentan nicht zur Verfügung. Daher kann kein Auszug
erstellt werden. Versuchen Sie es zu einem späteren Zeitpunkt erneut. Wir entschuldigen uns für die
Unannehmlichkeiten.»
FR: «Un ou plusieurs thèmes RDPPF sont momentanément indisponibles. L’extrait ne peut donc pas
être établi. Veuillez réessayer plus tard. Nous vous prions de nous excuser pour ce désagrément.»
The error handling exists in the print porxis for MFP. An adaption of the current text `a problem occurred while generating the pdf file` is needed depending on the language. See also https://github.com/openoereb/pyramid_oereb/blob/f5d65b35e6ab85cdaad54cf10ed6d00aac9fd549/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L134-L137

**Comment by jwkaltz** [comment]
@voisardf regarding "Set version to PDF/A-2a (or PDF/A-1 (ISO 19005-1:2005) if not possible)":

Our current underlying reporting technology, https://github.com/TIBCOSoftware/jasperreports, does not support PDF/A-2. 
The Weisung says "Der statische Auszug wird im Dateiformat PDF/A-1 ... oder PDF/A-2a ... erzeugt".

Reading that, it seems that we can simply stay with PDF/A-1, which we implemented with pyramid_oereb 1.5, see notes here: https://openoereb.github.io/pyramid_oereb/changes.html#mapfish-print-pdf-a-conformance

What do you think?

**Comment by voisardf** [comment]
@jwkaltz: Yes, the specifications allows to stay with PDF/A-1, and if the new standard is not supported yet by Jasper Reports we do not have a lot of options.
But we should keep an eye on that and 'upgrade' if Jasper Reports starts to support the new version.

**Comment by jwkaltz** [comment]
> we do not have a lot of options.

Just for completeness: a contribution by the openoereb community to JasperReports to support PDF/A-2 would be conceivable (but for sure non-trivial).
