### ISSUE TITLE
PDF: Topic Page

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1215]
Given the introduction of a third legal status, the topic page comes now in different 'flavours' depending on the status.
For each topic, subtopic and status providing results for this real estate a separate page has to be added in a predefined order.

?? Question to clarify with confederation: If a real estate is not touched by one ore two of the three legal status, but there are results contained in the bounding box (e.g. adjacent real estate is concerned) should the page be created anyway? 

Details on pages 15 ff and 24 of the specification: https://github.com/openoereb/pyramid_oereb/files/6442522/Weisung-statischer-Auszug-de.pdf

### What needs to be done:
- [x] Rearrange page title adding subtopic (if existing) and the legal state as subtitle -> PR #1306
- [x] Make sure the predefined titles from http://models.geo.admin.ch/V_D/OeREB/ > OeREBKRM_V2_0_Themen_[update_date].xml are used for the mandatory topics -> #1317
- [x] Remove complete legend element - remove `CompleteLegendLabel` and `legend`
- [x] Adapt legal document sorting to the new indexing system
- [x] Check that only the attribute title for legal documents is uses; official_title has been removed
- [x] Check that the official number is displayed as requested by the specifications -> this is given as a `MultilingualText`: it is what we currently have.
- [x] Verify layout conformance (spacing, padding, dimensions, font sizes)
- [x] Check for renamed attributes

**Comment by marionb** [comment]
> Check that the official number is displayed as requested by the specifications

@voisardf what is the `official number` is this th SR xxx number at the end of each "Gesetzliche Grundlagen"? 
If yes this already exists.

**Comment by voisardf** [comment]
@marionb  Yes, we are talking about this number, but I was not clear enough: How it is to be formatted is now given in detail.

**Comment by voisardf** [comment]
I can already tell that there will be an layout (spacing) issue with theme:subtheme combinations that are too long to fit on one line. I'll ask the confederation how to handle that.

**Comment by jwkaltz** [comment]
> I can already tell that there will be an layout (spacing) issue with theme:subtheme combinations that are too long to fit on one line. I'll ask the confederation how to handle that.

TIA for that clarification. However, can that be handled in a dedicated issue? (To avoid having issues and PRs being open very long)

**Comment by voisardf** [comment]
yes sure, we can treat that seperately 👍
