### ISSUE TITLE
New organisation and codes for themes and subthemes

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1218]
---

This point has to be analyzed regarding the special cases in TI (automatic sub theme code generation).

structure     | level
-------------- | --------------
ch.{topic}	|  federal level
ch.{canton}.{topic} | state level
fl.{topic} | Lichtenstein
ch.{bfsnr}.{topic} | municipality level

##### Consequences
---
* Code base needs to be reviewed
* Compatibility check with TI use case

**Comment by sasentom** [comment]
[ti028b_LandUsePlans.xlsx](https://github.com/openoereb/pyramid_oereb/files/6677537/ti028b_LandUsePlans.xlsx)

**Comment by sasentom** [comment]
Attached here is the file that we have prepared in order to exemplify what the themes and sub-themes for the Canton of Ticino will be called in the new framework model.
Inside the file there are two tabs:
- The current situation (v1.1) for the "PublicLawRestriction" feature. 
- A possible future solution (v2.0) for the "Thema" structure 

 

The mapping works. The main thing we want to underline is that the SubCodes 
- should NOT be managed statically in a config file as today;
- they should NOT be the basis for physically instantiating schemas in the database. Schemas must remain as they are today, that is one schema for each PLR theme (and eventually for each legal status).
- Instead, they must be able to be updated dynamically as today, in the "thema" table

**Comment by vvmruder** [comment]
I expect the target solution planned for pyramid_oereb 2.x will satisfy your needs. We plan to let pyramid_oereb dynamically spawn new themes out of the data field sub_theme. This means we should have some heavy test data to proof the small processing footprint on loops over all this themes. Maybe you can provide us some in the new model version soon?

**Comment by sasentom** [comment]
Here some test data, as we discussed: in the new model version, partial model Transferstruktur and separeted the list of subthemes for completion. It is an export from the official data, considering only the PLR land use plans in Grancia (fosnr = 5186). The two xtf files are already checked ok through ilivalidator 1.11.10.
[ti028b_LandUsePlans_RMv2_5186.zip](https://github.com/openoereb/pyramid_oereb/files/7083029/ti028b_LandUsePlans_RMv2_5186.zip)

**Comment by michmuel** [comment]
I started to write pyramid_oereb's models and sources for the direct access of the interlis transfer model. I intend to use the files provided in ti028b_LandUsePlans_RMv2_5186.zip as a first test dataset. The import of the xtf-files into PostGIS with ili2pg seems to work fine.

**Comment by michmuel** [comment]
@sasentom

I have a question concerning the data provided in ti028b_LandUsePlans_RMv2_5186.zip. Is the image in <BINBLBOX> (see example below from the trsf xtf) a valid png file?

<OeREBKRMtrsfr_V2_0.Transferstruktur.LegendeEintrag TID="25d27bef-5562-488f-b049-fc592c4dfd9f"><Symbol><BINBLBOX>89504E470D0A1A0A0000000D494844520000008E000000470806000000D11A7F740000045449444154789CED9CCF6B1D5514C7CFBD2F2FA43B9152775270315569A1228A452956BB90C2800BA9C54548323341C8C2854BA555FC13A475CCCC64577CBA1BA820EDA62BF147450B561EB8B0E8D69522E49139D78D292166EE9B7BE6CEEB7B2FDFCF32E7CE990FE1043277E67E551004260802925096E50707FD3C0CC3CBA2862D818F1D1F3EC3E1908220201586A109C350241245913AE8E759961951C396C0C78E0F9FB22C8988484B2598F92F4BF91F695F29F0B1E3DB473C384AA91F2CE51FA57DA5C0C78E6F1FF1E010D14D4BED568BBE52E063C7AB4F9BC119D4158C319FB5E82B053E76BCFA880687996FC471FC6B5D3D8EE35FC83EE15E81CFE47D4483A3946AF2F836B1474EF8D8E9C2473238D7E238BE336E5114455F1B6372417FF8CC808FEBE0DCADAAEADDA68BB7B7B7DF61E67B8EF780CF0CF8341E1C66BECFCC17D6D7D71B3FF36F6C6CFCDDEFF72F30F3EF4DAF81CF6CF8341D9CBB44F46292247F3495D8656565E537ADF54B9EFFB2E0F3907DC60E8E31E693AAAA5E9048EC1245D1FDD168F43C1165D21EF0992E9FDA7755C6985B5AEBF7D6D6D6BE910A1C449AA66794521F69AD5F76B90E3ED3E1B3FBAEEAC1E030F3486BFD9331E6A631E67A92243FFB14D84F51142799F912339F27A2535AEBC5BD75F84CA7CF6030585E5C5C7C8C88E84A97370473C76522BAD2E6950338C4607080080C0E1081C10122303840C4DE7D9C1D22BAF7DF7EC0E7ABABABDF2AA53AF936D618A38AA278CE18739199CF69AD9F26A2857DCBE033853E83C1E0D2D2D2D231DBC7EADF31F3FB49927CE55322CFF3D7AAAAFA506BFDACE3A5F099029FFF6D005AF8A2DFEFBFBDBCBCFC671B81344D8F6AAD3F554ABDDEA60F7C1EAE8FCB29873746A3D1F7699A9E904AE479FE54AFD7BBE3E197029F29F169F4CFB152EA78AFD7BB9D6599F3C9BDCDCDCD278D31B789E871D76BE133BD3E2E4F55C788E8C6D6D6D6230E128F12D1974474D4E13EF099011FD7C7F1277676763E6EBA582975552975DCF11E2EC0C74E673ECEFB384AA9B7F23C3F3B6E5D9EE7AF12D145D7FEF0990D1FE9F198030FAFEFC51833768D2FE063A70B1FE9F198B345519CACAB6759769A88CE487AC367367CC4AF1CAAAA7AD352B6D53A013E767CFBB47957F54A5D8199CFB5E82B053E76BCFAB4199C53C25A57C0C78E579F363127476A9BEEFB3E7612C0C78E6F1F7C560144607080080C0E10810CC08E98771F640076C4BCFB2003B03BE6DA071980DD31D73EC800840F3200C7001F3BC800844FF73EC800848FC8071980F011F92003103E221F6400C247E4830C40F838F92003103E221F64000229C800047230384004060788C0E00011181C20021980F071F24106207C443EC800848FC8071980F069E5830C40F8887C9001081F910F3200FD72687C9001081F910F32003BE030F82003103EC800B494E1830CC05AE063C7ABCFC270387CB01BE802333F4335A7FFCAB23CADF564DF9FC267323EC3E1908220A0852070DE23222222AD759F88544DAD276ADA02F8D8F1E5130401856148FF02964BCF8E641AD17E0000000049454E44AE426082</BINBLBOX></Symbol><LegendeText><LocalisationCH_V1.MultilingualText><LocalisedText><LocalisationCH_V1.LocalisedText><Language>it</Language><Text>Siepe naturale - boschetto</Text></LocalisationCH_V1.LocalisedText></LocalisedText></LocalisationCH_V1.MultilingualText></LegendeText><ArtCode>S_14_048_0008</ArtCode><ArtCodeliste>https://models.geo.ti.ch/DT/SIMBOLOGIA_28TI.xml</ArtCodeliste><Thema>ch.Nutzungsplanung</Thema><SubThema>ch.ti.ch08bf2v024100146</SubThema><DarstellungsDienst REF="692667"></DarstellungsDienst></OeREBKRMtrsfr_V2_0.Transferstruktur.LegendeEintrag>

**Comment by sasentom** [comment]
@michmuel 

It was supposed to be a valid png... but it is not the case in the past xtf, sorry! Thanks for your suggestion. I provide here a new datas
[ti028b_LandUsePlans_RMv2_5186_bis.zip](https://github.com/openoereb/pyramid_oereb/files/7261223/ti028b_LandUsePlans_RMv2_5186_bis.zip)
et

**Comment by michmuel** [comment]
@sasentom
Thanks for updating the data!

**Comment by vvmruder** [comment]
Since we implemented it this can be closed. Feel free to reopen if there is something pending.
