### ISSUE TITLE
model changes for documents

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1220]
---
subdivision for document and document_base falls away.

*OLD*
attributes OfficialTitle, Canton, Region and Municipality abandoned

*NEW*
MANDATORY attribute TYPE (law, provision, hint)
MANDATORY attribute INDEX to define display order

* INDEX applies to `sort_within_themes_method` of the extract element of the pyramid oereb standard model

##### Consequences:
---
* Models needs to be refactored
* Document sorting needs to be refactored
* Changes regarding the Öreblex source?

**Comment by jwkaltz** [comment]
@vvmruder is this redundant to #1176 ?

**Comment by voisardf** [comment]
@jwkaltz @vvmruder yes it is. we could fusion it with https://github.com/openoereb/pyramid_oereb/issues/1176 which is a little bit mor detailed

**Comment by vvmruder** [comment]
Yes-I'am still in phase of gathering. So I will consolidate in a next step. Probably I will merge several issues.

**Comment by vvmruder** [comment]
We can close this, since all info is in mentioned issue
