### ISSUE TITLE
Topic listing in categories 'theme not concerned' and 'theme without data'

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1221]
a topic is ONLY listed in one of this two categories, if the category applies to ALL three legal states the same.

#### Issue:
- If a topic appears in `concerned themes` with one of the thee legal states (`in Kraft`, `anderung mit vorwiking`, `änderung ohne vorwirkung`) it can not appear in `theme not concerned` nor in `theme without data`

#### Example:
- The image below has `Grundwasserschutz (Rechtskräftig)` as a `concerned theme` => `Grundwasserschutz (Rechtskräftig)` can not appear in `theme not concerned` and `theme without data`

![TopicList](https://user-images.githubusercontent.com/1460598/132686268-40892a6a-36ca-4660-8c4d-21d73864c12c.png)

TODO:
- [ ] create test data
- [x] check if this is tested for in the extract code
- [x] test for sub-topicas and their topics - this is probably the only case that is not fulfilled.

**Comment by marionb** [comment]
@vvmruder or @voisardf Do you know how the situation is for sub-topics and the corresponding topic?
If a sub-topic is in the list of `concerned themes` will the topic not be allowed to appear in `theme not concerned` or in `theme without data`? 

_I think this would correspond to the current situation._

**Comment by voisardf** [comment]
@marionb : yes, subtopics are only child elements - so the rules of the theme apply: if data is published for the municipality for one of the law status of a theme, the theme must not appear in 'without data'.
The same goes for 'not concerned': A theme only appears under not concerned in the TOC, if none of it's combinations Theme:subtheme & law_status touch the selected real estate. - but only the combinations concerning the property should be listed in the TOC under concerned - all other combinations are omitted. 

See also page 14 of the specification"statischer Auszug", point 3.3.1 for the allowed combinations: https://github.com/openoereb/pyramid_oereb/files/6442522/Weisung-statischer-Auszug-de.pdf
