### ISSUE TITLE
Integrate new test dataset

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1224]
To be able to test and validate we need test data which fits the new data model.

The data should be embedded in description of #1195

**Comment by voisardf** [comment]
@vvmruder First draft of new table creation and sample data for contaminated sites (public).

[20210630_contaminated_sites.zip](https://github.com/openoereb/pyramid_oereb/files/6742165/20210630_contaminated_sites.zip)

but we should also have à look at page 46 of the Rahmenmodell where suggestions for the configuration are given. There are multilingual value lists suggested for the document types, the default disclaimer and others. Might be we want to integrate this too

**Comment by vvmruder** [comment]
Done => Close
