### ISSUE TITLE
Certification becomes optional

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1225]
---
Certification ist no mandatory option anymore.

Should related element be removed from the code?

##### Consequences:
---
* Code could be cleaned - not mandatory

Do a poll to be sure nobody needs this feature now and in the future. => Maybe we can keep it in code to offer it for future use, it shouldn't be so heavy

**Comment by jwkaltz** [comment]
@vvmruder I think we should remove it, to my knowledge it has not been validated that the current implementation is useful.

**Comment by voisardf** [comment]
I agree with you but I would wait for the answer of the user group

**Comment by vvmruder** [comment]
AS for now we can keep code like it is. Certification is optional, so nothing needs to be done
