### ISSUE TITLE
Upgrade geoalchemy

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#1229]
pyramid_oereb seems to be currently not compatible with geoalchemy 0.9.0, in the CI tests there are errors like the following:

`E       psycopg2.errors.SyntaxError: syntax error at or near "limit"
E       LINE 1: ...e_limit ON pyramid_oereb_main.real_estate USING GIST (limit)
E                                                                        ^

/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py:717: SyntaxError

The above exception was the direct cause of the following exception:

    @pytest.mark.run(order=-2)
    def test_create_standard_db():
        assert pyramid_oereb_test_yml is not None
        from pyramid_oereb.standard import create_tables_from_standard_configuration
>       create_tables_from_standard_configuration(pyramid_oereb_test_yml)

tests/test_standard_db_creation.py:11: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyramid_oereb/standard/__init__.py:107: in create_tables_from_standard_configuration
    main_base_class.metadata.create_all(main_schema_engine)
`

**Comment by vvmruder** [comment]
Is this still relevant?
