### ISSUE TITLE
getegrid for Identdn and Number not working

### ISSUE THREAD

**Issue by LieGeo** [openoereb/pyramid_oereb#1234]
I' m testing the pyramid_oereb webservice, especially "getegrid" by  IDENTDN and NUMBER.

In pyramid_oereb/views/webservice.py , there is a function "get_egrid_ident", but the request width IDENTDN and number is answered   with "400 Bad Request"
URL Example   oereb/wsgi/oereb/getegrid/json/?identdn=FL0200000044&number=141

Any hint on how to fix this? Or is the URL malformed?
Peter

**Comment by voisardf** [comment]
I think you have to use the old specification: https://sitn.ne.ch/crdppf/getegrid/json/NE125033/5033

**Comment by LieGeo** [comment]
works fine. thank you

**Comment by voisardf** [comment]
👍
