### ISSUE TITLE
Test for import of federal topics fails

### ISSUE THREAD

**Issue by kdeininger** [openoereb/pyramid_oereb#1253]
The following test fails:

```
FAILED tests/xtf_import/test_federal_topic.py::test_load - SystemExit: 1
```

This is related to the state of the project being partially adapted to the new specification. After the adaption of all database models and sources, the import script and its tests can be fixed.

**Comment by vvmruder** [comment]
Since this is not offered any longer through pyramid_oereb we can close this issue right away. Import is now done through ili2pg and will be documented.
