### ISSUE TITLE
Create Theme element in pyramid_oereb ecosystem

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1256]
Because the subtheme is now of the type Theme (Record) in the extract we need some additional construction to get the data from somewhere.

The decision is to implement it via a table in the main schema and have a semi/soft  Foreignkey relation. This means we need an additional Model in the `pyramid_oereb.standard.models.main.py`

This means:

- implement a model fitting the needs of the already existing theme record (attributes code and text, where text is multilingual so JSONType in model)
- implement a fitting source (get idea how this might work from the glossary database source)
- implement a fitting reader (get idea how this might work from the glossary reader)
- get everything together in the processor => This means before everything else get all records of themes, and pass them to the PLR-Source, they will be needed there => This means to adapt complete behavior of the PLRSource from its real base class to all its child implementations.

### Pseudocode

Model
------

class Theme():
  id = PrimaryKey
  code = string + unique constraint
  text = JSONType

**Comment by vuilleumierc** [comment]
References:
1. Rahmenmodell-de.pdf, page 46: table `Theme`
<img src="https://user-images.githubusercontent.com/18527151/125416852-5b3bb057-3096-4c67-98b5-66e004b319f2.png" width="400">
2. Rahmenmodell-de.pdf, page 35: value range for theme codes
<img src="https://user-images.githubusercontent.com/18527151/125417749-3445852a-43f8-4cb9-a9c0-e5a09b5a9fc6.png" width="400">
3. Rahmenmodell-de.pdf, page 35: reference to a theme or subtheme
<img src="https://user-images.githubusercontent.com/18527151/125418222-ad9fd9aa-70e5-4dc4-80d9-5cef17791876.png" width="400">
4. XML model

http://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Themen.xml

**Comment by vvmruder** [comment]
As little addition, I would prefer a `id` column as primary key which generates the key through a sequence, and a unique constraint on the `code` column.

But this is only a suggestion. Maybe we can also use the `code` column as primary key.

**Comment by vvmruder** [comment]
About ThemaRef => I'am not sure what this is for. In Database we have the relation via foreign keys.

@voisardf & @kdeininger : Any suggestions?

**Comment by kdeininger** [comment]
The type `ThemaRef` is only used in this model in the topic `Konfiguration`:

http://models.geo.admin.ch/V_D/OeREB/OeREBKRMkvs_V2_0.ili

This topic is only meant as a suggestion, so I think we can ignore it.

**Comment by voisardf** [comment]
We just realized with @vuilleumierc that we use the theme code (homemade englisch in pyramid_oereb v1.x) to name and create the standard schemes. 
Using the new federal code (german, predefined, long and with separators) for v2 seams not a particularly good choice. We should discuss that in the next daily.

There are also other dependency questions to resolve

**Comment by vvmruder** [comment]
@voisardf I addressed this issue in PR https://github.com/openoereb/pyramid_oereb/pull/1248

The models/schemas will have a dedicated config for the schema name to omit this issue.
