### ISSUE TITLE
DocumentTypText handling

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1262]
The document type text is configured in the yml today:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/standard/pyramid_oereb.yml.mako#L63-L87

The new [XML](http://models.geo.admin.ch/V_D/OeREB/OeREBKRM_V2_0_Texte.xml) containing text definitions provided by federation offers better possibilities then storing this mapping hardcoded in the yml.

The new approach should be like for municipalities and glossaries.

New Model in the main.py with model name:

- `DocumentTypeText `

and attributes:

- `code` (PrimaryKey, String)
- `text`(multilingual/JSON)

The matching should reflect the three types:

- Rechtsvorschrift
- GesetzlicheGrundlage
- Hinweis

In addition the places where usage and reference to this exists need to be cleaned and updated to support now this three options. This is mainly the part of the rendering:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/lib/renderer/extract/json_.py#L332
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/lib/renderer/extract/templates/xml/document.xml#L4

The mapping part can be removed from the config:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/standard/pyramid_oereb.yml.mako#L63-L87

Test data needs to be adapted. The content can be consumed out of the XML file.

The new approach should use a reader and a source as it is used for e.g Glossary.

A config part should be added to the yml like it exists for e.g. Glossary:
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/standard/pyramid_oereb.yml.mako#L380-L391

Dedicated methods should offer access to the document type texts stored in database directly at the config object. This can be `get_document_type_texts`

**Comment by voisardf** [comment]
Here is the postgres data with the document_types
[pyramid_oereb_sample_document_types.zip](https://github.com/openoereb/pyramid_oereb/files/6824023/pyramid_oereb_sample_document_types.zip)
