### ISSUE TITLE
Patch-Changes on OeREBKRM_V2_0_Texte.xml and OeREBKRM_V2_0_Themen

### ISSUE THREAD

**Issue by vvmdipie** [openoereb/pyramid_oereb#1269]
Swisstopo have just informed that there are Patch-Changes on OeREBKRM_V2_0_Texte.xml a OeREBKRM_V2_0_Themen

German:
Mit dem Start der Umsetzung des revidierten Rahmenmodells haben wir Fehler in den Dateien OeREBKRM_V2_0_Texte.xml und OeREBKRM_V2_0_Themen.xml gefunden.
Es handelte sich insbesondere um Schreibfehler und Übersetzungsfehler die bislang nicht aufgedeckt wurden.
Zudem wurde uns vom BFE ein Fehler im Attribut «Code» für die zwei neuen Bundesthemen gemeldet.
Bei der Änderung handelt es sich um einen Patch-Change. Die zwei korrigierten XML-Dateien wurden bereits im Modell-Repository publiziert, sie weisen neu die Ergänzung «_20210714» auf. Die alten Kataloge sind in das Unterverzeichnis /replaced verschoben worden.

French:
Avec le début de la mise en œuvre du modèle-cadre révisé nous avons trouvé des erreurs dans les fichiers OeREBKRM_V2_0_Texte.xml et OeREBKRM_V2_0_Themen.xml.
Il s’agit en particulier de fautes de frappe et d’erreurs dans les traductions qui n’avait pas été identifiées.
De plus l’OFEN nous a communiqué une erreur dans l’attribut « Code » des deux nouveaux thèmes fédéraux.
Il s’agit d’une modification de type Patch-Change. Les deux fichiers XML corrigés ont d’ores et déjà été publié dans le Modell-Repository, les deux fichiers comporte le supplément «_20210714». Les anciens catalogues ont été déplacés dans le sous-dossier /replaced.

**Comment by vvmruder** [comment]
Done => Close
