### ISSUE TITLE
PDF Table of Content: add QR-Code

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#1270]
The specification defines an optional QR-Code.
The current version of pyramid_oereb / pyramid_oereb_mfp has first implementation elements for rendering such a QR-Code, but there is no actual implementation for filling the QR-Code with content on the side of pyramid_oereb.
- [ ] Produce QR-Code in pyramid_oereb,
- [ ] Check / adapt QR-Code in pyramid_oereb_mfp print templates, format according to new specification
- [ ] Verify QR-Code stays backward compatible

**Comment by vvmruder** [comment]
Probably the correct library for producing the QR code would be this one: https://pypi.org/project/qrcode/

The URL should be the pdf URL.

Still in discussion is, if this could be the dynamic extract URL.

**Comment by vvmruder** [comment]
solved by https://github.com/openoereb/pyramid_oereb/pull/1579
