### ISSUE TITLE
Catch server crash on not existing default language

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1275]
If the server is configured with a default language which is actually not in the data, the server crashes. This should be handled with a catch. It should gracefully issue a message to the client that default language was not found in the data. A log message error should be added to the server logs.

**Comment by marionb** [comment]
@vvmruder I gave this some more thought to this. (As I don't have a PR yet I add it here in the issue)
I see two possibilities to solve this:
1. Make sure that the values are available when the DB is configured so the sever will never end up in this state. What do you think of the possibility to add a constraint on all the field defined as the standard language in the db? (I am a bit in doubt about this option there might be a lot of pit falls) 
2. The other option would be to just fetch all the the elements of a certain language with a special `get` function which checks if the value exists in that language and handles it accordingly. I think this will need a lot of care not to miss any thing.

In the end we will probably need a combination of the two.
