### ISSUE TITLE
Fix tests related to xml and xtf

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb#1276]
Fix tests:

![Screenshot from 2021-07-21 16-16-43](https://user-images.githubusercontent.com/77100084/126619067-0cab5382-9ff0-4926-8cfc-e8bf4b0cfac4.png)

**Comment by vvmruder** [comment]
Since XTF import is not offered any more by pyramid_oereb we do not need to fix the tests. They are removed already. Regarding XML testing. I think this will be solved by core tests. @vuilleumierc What do you think-can we close this?
