### ISSUE TITLE
How to organize tests

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1300]
What ideas or best practices do you know to re implement the testing of pyramid_oereb project. Especially how to handle test data, unit tests and schema tests for extract validation.

Feel free to add your suggestions in the comments - links, documents, ideas.

@voisardf
@vuilleumierc 
@marionb 
@michmuel 
@kdeininger 
@svamaa 
@jwkaltz

**Comment by jwkaltz** [comment]
@vvmruder some thoughts on this issue after discussion with @vuilleumierc and @marionb , although only partially related to your question:
* pyramid_oereb is missing true integration tests, see #1174, that would be a big plus for the automatic pull requests (dependencies),
* the code test coverage should probably be increased, it would be good to define a target for that, perhaps differentiating between functional area (notably, what is our expectation regarding the packages in "contribs")

**Comment by vvmruder** [comment]
We solved this already with the new project structure.
