### ISSUE TITLE
[DOC] - Theme sample data 

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1309]
### B.3.4 Thema
Wertebereich für den Code eines Themas oder Subthemas. Aufgrund des Codes lässt sich nicht erkennen, ob es ein Thema oder Subthema ist.

Thema = TEXT*120;
Der Code wird nach folgendem Muster gebildet:
ch.{topic}               | Für (Sub-)Themen des Bundes
-------------------- | ----------------------------------
ch.{canton}.{topic} | Für (Sub-)Themen der Kantone
fl.{topic}                | Für (Sub-)Themen Liechtensteins
ch.{bfsnr}.{topic}   | Für (Sub-)Themen der Gemeinde

Wobei {canton} das offizielle zweistellige Kürzel des Kantons ist (z.B. «SO»), {topic} der Themenname und {bfsnr} die Gemeindenummer gemäss offizieller Gemeindeliste des BFS.
Gross/Kleinschreibung ist signifikant (darf nicht ignoriert werden).

### Examples

ch.Nutzungsplanung | Nutzungsplanung (kantonal/kommunal)
ch.ProjektierungszonenNationalstrassen | Projektierungszonen Nationalstrassen
ch.BaulinienNationalstrassen | Baulinien Nationalstrassen
ch.ProjektierungszonenEisenbahnanlagen | Projektierungszonen Eisenbahnanlagen

ch.ne.KantonaleBaulinien | Plans d'alignement cantonaux
ch.261.GeschuetzteAussichtspunkteZuerich | Geschützte Aussichtspunkte Stadt Zürich

**Comment by vvmruder** [comment]
Done => Close
