### ISSUE TITLE
Check png transparency and pdf/A-1 compliance

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1311]
As follow-up to PR https://github.com/openoereb/pyramid_oereb/pull/1305 we still have an PDF format compliance issue.
We need to make sure the used logos and all other binary elements in the static extract are PDF/A-1 compatible.

**Comment by voisardf** [comment]
Maybe we should move this issue to the pyramid_oereb_mfp project?
Unless the WMS requests returns map images with transparency?

**Comment by vuilleumierc** [comment]
New logos to test (2021.09.03): 
[OeREBKRM_V2_0_Logos_20210903.txt](https://github.com/openoereb/pyramid_oereb/files/7152344/OeREBKRM_V2_0_Logos_20210903.txt)

**Comment by vuilleumierc** [comment]
I decoded the images from OeREBKRM_V2_0_Logos_20210903.xml and there is still transparency in the ch.plr logos (all languages) so it is still not possible to comply with PDFA-1. Here are the images:

![ch de](https://user-images.githubusercontent.com/18527151/133260968-5514b6a1-325b-4ae7-9f98-9152d8d45093.png)
![ch fr](https://user-images.githubusercontent.com/18527151/133260971-bde96039-5bfb-4470-bc46-9bf46f9bf374.png)
![ch it](https://user-images.githubusercontent.com/18527151/133260973-01dfeaeb-18ae-4b38-b6c1-6ef5c9c068b6.png)
![ch plr de](https://user-images.githubusercontent.com/18527151/133260978-e8f1d367-4d28-4a59-82b4-8b615c3f8f28.png)
![ch plr en](https://user-images.githubusercontent.com/18527151/133260981-f20633e2-1bab-4fbd-b343-fbff3b72c283.png)
![ch plr fr](https://user-images.githubusercontent.com/18527151/133260982-85c62c95-47f9-475a-89f0-e0fee18e376a.png)
![ch plr it](https://user-images.githubusercontent.com/18527151/133260986-27f40632-95e4-4483-bc24-919410330de9.png)
![ch plr rm](https://user-images.githubusercontent.com/18527151/133260990-0742023a-84c5-4c5f-b781-3b3c2b46cee1.png)
![ch rm](https://user-images.githubusercontent.com/18527151/133260993-22e4e59e-8fad-4f06-9633-87d0b276551b.png)
