### ISSUE TITLE
Use "publication_date" for "published_from"?

### ISSUE THREAD

**Issue by kdeininger** [openoereb/pyramid_oereb#1335]
Currently, using OEREBlex the value for the document attribute `published_from` is mapped from the OEREBlex attribute `enactment_date`. OEREBlex also offers the attribute `publication_date`, which seems to fit better to `published_from` by its meaning.

Should we

- replace `enactment_date` with `publication_date`,
- specifiy via configuration which attribute to use or
- just keep the existing solution using `enactment_date`?

**Comment by vvmruder** [comment]
@kdeininger What is the status of this?
