### ISSUE TITLE
provide logs when configuration is faulty

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#1381]
The V2 should always provide at least a log entry of level warning or error when the configuration is faulty.

Candidates for improvements: 
* config.py

Possible improvements:
* At the moment a `ConfigurationError` is thrown if a config table does not exists in the DB, but not if the table exists and is empty -> add a log entry or an error for such cases

**Comment by svamaa** [comment]
https://github.com/openoereb/pyramid_oereb/pull/1869
