### ISSUE TITLE
JSON-Extract not valid according to JSON-Schema

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb#1382]
**LegalProvisions.Type.Code and LegalProvisions.Lawstatus.Code**
Error messages from VSC when JSON-extract is copied to VSC:
String does not match the pattern of "LegalProvision|Law|Hint".
Value is not accepted. Valid values: "inForce", "changeWithPreEffect", "changeWithoutPreEffect".

Where should the translation be implemented?
Here? https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/standard/sources/document.py

**Geometry**
Should be optional.

**Comment by vvmruder** [comment]
It should be similar as in the xml rendering process. Methods are all existing already.

**Comment by vvmruder** [comment]
In your case, did you checked if the XML delivers the values translated correctly?
