### ISSUE TITLE
subunit_of_land_register_designation not multilingual

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#1388]
The attribute `subunit_of_land_register_designation` in the table `real_estate` (Class `RealEstate` respectively) is of type String and not JSONType. Therefore only one language can be inserted here. Unfortunately we in Bern do have the subunit (Grundbuchkreis) and we are multilingual. Is there a possibility to make `subunit_of_land_register_designation` multilingual?

**Comment by vvmruder** [comment]
Hi @peterschaer 
Does this apply also to subunit_of_land_register? Or should subunit_of_land_register_designation be the only attribute which is multilingual in this context?

**Comment by peterschaer** [comment]
No it does not apply to subunit_of_land_register. Only subunit_of_land_register_designation is multilingual.

**Comment by vvmruder** [comment]
Ok. Should we put it in the pipe as an enhancement? To be clear: This is out of scope of the current project. But I can imagine to see this feature in pyramid_oereb.

**Comment by voisardf** [comment]
I'll Check with swisstopo if the model should be adapted

**Comment by voisardf** [comment]
It appears that this point is not an issue for the multilingual cantons. They all have either no need or a workaround for it as it seems.
