### ISSUE TITLE
Fix and enhance test for contrib.data_sources.swisstopo

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1395]
Due to new project structure its possible to run test for specific parts of the application. This task is for the contrib.data_sources.swisstopo

- move tests depending to core part into the new dir
- fix all broken tests
- add tests where necessary to raise coverage

**Comment by vvmruder** [comment]
Can be removed if not used.

**Comment by lopo977** [comment]
We are using the Swisstopo Address data source. (Tessin)

**Comment by jwkaltz** [comment]
Aargau is also using the swisstopo address data source (@thomasmarti )

**Comment by michmuel** [comment]
We use it as well (BL).

**Comment by peterschaer** [comment]
We don't use this data source (BE).
