### ISSUE TITLE
Fix and enhance test for contrib.print_proxy.xml_2_pdf

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1397]
Due to new project structure its possible to run test for specific parts of the application. This task is for the contrib.print_proxy.xml_2_pdf.

- move tests depending to core part into the new dir
- fix all broken tests
- add tests where necessary to raise coverage

**Comment by vvmruder** [comment]
Only to test the code as unit tests without direct relation to the external service.

**Comment by jwkaltz** [comment]
Note about service: by request of Glarus, I was in contact with GIS Daten AG to enquire about using the service with the new schema, here is the info from Marco Dellenbach:

Wir haben den PDF Service für unseren Eigenbedarf bereits weiterentwickelt und dieser kann prinzipiell bereits das Schema 2.0 verarbeiten. Die URLs für Schema 2.x bleiben gleich wie für 1.x

https://oereb-pdf.gis-daten.ch/oereb/report/form bzw. https://oereb-pdf.gis-daten.ch/oereb/report/create
Der Service erkennt selbständig, ob es sich um einen neuen Dataextract 2.x handelt.

**Comment by vvmruder** [comment]
@jwkaltz is this solved by https://github.com/openoereb/pyramid_oereb/pull/1619 ?

**Comment by jwkaltz** [comment]
> @jwkaltz is this solved by #1619 ?

Not as such, in fact that PR did not change the xml2pdf proxy code. However, the xml2pdf service does now have a "real life" test with the current code of pyramid_oereb in Glarus. 
An (automated) test would help to increase the code coverage, of course, but I'm not sure it's worth it for this specific function.

**Comment by voisardf** [comment]
We will ask the usergroup if someone is still using it. Else treat it as deprecated and delete it.

**Comment by svamaa** [comment]
As feedback from the Usergroup, no one uses xml2pdf anymore. We can drop support for this.
