### ISSUE TITLE
Subtheme handling in mfp print proxy

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#1430]
In Berne we have to use subthemes in land use plans. We have the following subthemes defined:

![themes](https://user-images.githubusercontent.com/3659322/145399752-a1bb38e7-70b3-4e90-9a0e-df71796b0c42.png)

As you can see the title field is a combination of the theme's title (e.g. "Kommunale Nutzungsplanung") and the subtheme's title (e.g. "Zonenflächen der Grundnutzung"). The title is concatenated because in the extract (as defined in the Weisung DATA-EXTRACT) for each plr there are only the attributes Code, SubCode and Text.

![theme_xml](https://user-images.githubusercontent.com/3659322/145399794-698927e0-aaab-4b2b-ac6b-45585c99721a.png)

There is only a single text attribute. So there is no possibility to have the theme title and the subtheme title separately. Therefore we have to combine them in this single attribute. The problem now is with the mfp print_proxy where the theme title and the subtheme title are concatenated:
https://github.com/openoereb/pyramid_oereb/blob/e67281821c635d7d64d2e9f33e28242178a3bfc9/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L381
In our cases that produces quite a redundant PDF output:

![theme_title_pdf](https://user-images.githubusercontent.com/3659322/145399821-2911b8e5-0f9a-4bda-9535-2b2ee71891fc.png)

I suspect that the print_proxy is only able to do this because there's probably a bug in the JSON (s. #1426) in case of subthemes. If this will be fixed according to the Weisung there won't be enough information in the JSON to do this concatenation. So there is a link to #1426 and maybe also with #1368 
So my proposal is to omit the concatenation of theme title and subtheme title in the mfp print_proxy

**Comment by peterschaer** [comment]
The fix in #1432 has also corrected this issue. There is no more concatenation in the print proxy. For me this is ok, so I close the issue.

**Comment by lopo977** [comment]
I am integrating this modify. I have to double check w/ my business past @Marco Tommasini, if removing concatenation could generate some issue to Canton Tessin

**Comment by lopo977** [comment]
Dear all, 
both implementations are viable, but we'd prefer if the field text contains only the subtheme text (in case of).
If we have the theme and subtheme decode (text) separated, I'd better to manage/display in other implementation e.g. oereb-viewer.
Having in text field both theme and subtheme together there is a redundancy.

Is it possible to evaluate the previous implementation, please? 
Thank you in advance.
Regards.
