### ISSUE TITLE
entries in table theme_document are not mandatory

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb#1442]
Entries in tables documents and theme_documents in the main schema are not mandatory although that will probably be the normal case. However, someone could start with cantonal themes only where all the documents are directly related to the PLR. This will cause an error.

I suggest to add an if statement to handle this case at https://github.com/openoereb/pyramid_oereb/blob/9d6d3138e4d70b1ffbed203cb1ca7120985bde43/pyramid_oereb/core/config.py#L133

**Comment by vvmruder** [comment]
@michmuel I assume this is an actually happening error? You tried it with cantonal data only and it fails?

**Comment by michmuel** [comment]
```
.venv/lib/python3.7/site-packages/pyramid_oereb/core/config.py:70: in init
    Config.assemble_relation_themes_documents()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    @staticmethod
    def assemble_relation_themes_documents():
        for theme in Config.themes:
            theme_documents = []
>           for theme_document in Config.theme_document:
E           TypeError: 'NoneType' object is not iterable
```

**Comment by michmuel** [comment]
If there is no entry in table "theme_document", then Config.theme_document is None.

**Comment by vvmruder** [comment]
We could work around if we initially set the variables not None but as empty list. What do you think? This would reflect the reality better anyhow.

**Comment by michmuel** [comment]
I would add "if theme_document is not None:" in line 131. If it's none, the complete following part is obsolete.

**Comment by vvmruder** [comment]
:ok_hand: Better. I had a quick look. Changing it to be initially empty list has sveral side effects. I will add part as you suggested.
