### ISSUE TITLE
[DOC] - New links to federal data files

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#1448]
Hi all,

here are the new download links for the federal data version 2.0:

    - name: plr87
      code: MotorwaysProjectPlaningZones
	  download: https://data.geo.admin.ch/ch.astra.projektierungszonen-nationalstrassen_v2_0.oereb/data.zip
    - name: plr88
      code: MotorwaysBuildingLines
      download: https://data.geo.admin.ch/ch.astra.baulinien-nationalstrassen_v2_0.oereb/data.zip
    - name: plr96
      code: RailwaysProjectPlanningZones
      download: https://data.geo.admin.ch/ch.bav.projektierungszonen-eisenbahnanlagen_v2_0.oereb/data.zip
    - name: plr97
      code: RailwaysBuildingLines
      download: https://data.geo.admin.ch/ch.bav.baulinien-eisenbahnanlagen_v2_0.oereb/data.zip
    - name: plr103
      code: AirportsProjectPlanningZones
      download: https://data.geo.admin.ch/ch.bazl.projektierungszonen-flughafenanlagen_v2_0.oereb/data.zip
    - name: plr104
      code: AirportsBuildingLines
      download: https://data.geo.admin.ch/ch.bazl.baulinien-flughafenanlagen_v2_0.oereb/data.zip
    - name: plr108
      code: AirportsSecurityZonePlans
      download: https://data.geo.admin.ch/ch.bazl.sicherheitszonenplan_v2_0.oereb/data.zip
    - name: plr117
      code: ContaminatedMilitarySites
      download: https://data.geo.admin.ch/ch.vbs.kataster-belasteter-standorte-militaer_v2_0.oereb/data.zip
    - name: plr118
      code: ContaminatedCivilAviationSites
	  download: https://data.geo.admin.ch/ch.bazl.kataster-belasteter-standorte-zivilflugplaetze_v2_0.oereb/data.zip
    - name: plr119
      code: ContaminatedPublicTransportSites
      download: https://data.geo.admin.ch/ch.bav.kataster-belasteter-standorte-oev_v2_0.oereb/data.zip

happy integration 😉

**Comment by voisardf** [comment]
Official page: https://api3.geo.admin.ch/services/oerebservices.html

**Comment by vvmruder** [comment]
Done
