### ISSUE TITLE
xml extract

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb#1455]
There is an error in our test application (canton BL, version of pyramid_oereb: current master) when ".../extract/xml?EGRID=..." is invoked.

Displayed mako runtime error:

```
Error !
TopLevelLookupException: Cant locate template for uri 'extract.xml'
260
                    return self._load(srcfile, uri)
261
            else:
262
                raise exceptions.TopLevelLookupException(
263
                    "Cant locate template for uri %r" % uri
264
                )
265

266
    def adjust_uri(self, uri, relativeto):
267
        """Adjust the given ``uri`` based on the given relative URI."""
268

/app/.venv/lib/python3.7/site-packages/mako/lookup.py, line 263:
263
"Cant locate template for uri %r" % uri
/app/.venv/lib/python3.7/site-packages/pyramid_oereb/core/renderer/extract/xml_.py, line 76:
76
template = templates.get_template('extract.xml')
/app/.venv/lib/python3.7/site-packages/pyramid_oereb/core/renderer/extract/xml_.py, line 61:
61
content = self._render(extract, self._params_)

```

**Comment by vvmruder** [comment]
First checks show: http://localhost:6543/oereb/extract/xml?EGRID=CH113928077734 is working like expected on master.

What else you can provide as useful information to trace the error?

**Comment by mki-c2c** [comment]
hard to debug without access to the system - what's the setup of the app ?
Some ideas:
- can there be a problem with access rights to the template folder ?
- how is the oereb package installed (with or without symlink: pip install vs. pip install -e)
- are there any subtle options in setup.py to install or not the static templates ?
as said, it's working locally for me, the resolver is able to find the packaged template resources

next step would be to debug and check the resolver path [self.template_dir](https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/core/renderer/extract/xml_.py#L72)

**Comment by michmuel** [comment]
https://pypi.org/project/pyramid-oereb/2.0.0b7/#files : in the tar-file at /pyramid_oereb-2.0.0b7/pyramid_oereb/core/renderer/extract/ there is no folder "templates/xml" at https://pypi.org/project/pyramid-oereb/2.0.0b7/#files

Should https://github.com/openoereb/pyramid_oereb/blob/master/MANIFEST.in be adapted?
