### ISSUE TITLE
KBS military/civil aviation - area and point features with same type_code

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb#1463]
Hi all

I believe we have an issue with the KBS military data, available for the canton SG. 
The issue relates to the fact, that area and point geometries both can have the same type_code, if they have the same StatusAltlVx. 

Unfortunately we have real estates, where point and area geometries with the same type_code exist. The geometries are then not displayed correctly in the static extract, since they all have the same type_code (https://oereb.geo.sg.ch/ktsg/wsgi/oereb/extract/reduced/pdf/CH327773683163) 
![image](https://user-images.githubusercontent.com/54711581/148057953-e943af13-ef02-488f-862d-c066f13d6bde.png)

I checked the topic with camp2camp and swisstopo already. Wolfang from camp2camp mentioned, that he thought, that the data will change, so that one unique type_code will be available per geometry type and StatusAltlVx. But this apparently will not be the case.
Answer from swisstopo here: 
"In den neuen Weisungen seit Mai 2021 verlangt swisstopo, dass die Kantone beide Geometrietypen desselben Themas unterscheiden und entsprechend ausweisen. Dies betrifft den KbS-BAZL und den KbS-Militär, wo es Punkt- und Flächenobjekte gibt. Jeder Eigentumsbeschränkung wird im Rahmenmodell (Transferstruktur) ein Legendeneintrag zugeordnet. Weil eine einzelne Eigentumsbeschränkung gemäss Definition nie aus unterschiedlichen Geometrietypen bestehen darf, wird ihr somit entweder ein Legendeneintrag mit einem Punktsymbol oder ein Legendeneintrag mit einem Flächensymbol zugewiesen (der Legendentext kann dabei identisch sein, weil es z.B. gelbe Punkte und gelbe Flächen gibt). Die ÖREB-Daten des KbS-Militär werden nur in dem Sinne umstrukturiert, wie sich das Rahmenmodell von der Version V1.1 zu V2.0 verändert hat, weitergehende Anpassungen sind nicht vorgesehen.

Weil die ÖREB-Daten des KbS-Militär nach neuem Rahmenmodell seit Anfang Dezember aufgeschaltet sind, hilft vielleicht der Link (https://data.geo.admin.ch/ch.vbs.kataster-belasteter-standorte-militaer_v2_0.oereb/), um dies bei sich auszuprobieren."

I checked the new data from the link provided and there are separate legend entries available for point/area features, but they still have the same type_code.

So I assume there is a change needed, which does not only account for type_code but also for geometry typ, when checking for PLRs? 
I hope I was able to explain the issue clearly - if there are questions, please let me know.

Thanks & Cheers
Max

**Comment by voisardf** [comment]
We have this case for civil aviation KBS https://sitn.ne.ch/crdppf/extract/reduced/pdf/CH646970776677

We already exposed the problematic last summer, but the answer from Swisstopo (and Claude Eisenhut) was, that from the modelling point of view, this cases can be handled. That is certainly true in theory, but needs some extra work regarding either data integration, or on the extract preparation side. 😞

**Comment by voisardf** [comment]
on pyramid_oereb side, I think the idea was to have an unique id for each legendentry regarding it's combination of geometry type and type_code.
But I'm realizing now that we do not pass the legend entry id in the extract data (right? @jwkaltz @vvmruder) so grouping by that element is not possible in the PDF extract as of now

**Comment by vvmruder** [comment]
I think we had the idea of grouping it by the type_code. Which must be unique on data import. If you have a PLR in a topic with legend text Typ1 but which can have point and line for instance than there must be legend_entries like
`[{'legend_text': "Typ1", 'type_code': "typ1_line", 'symbol': <line_symbol>}, {'legend_text': "Typ1", 'type_code': "typ1_point", 'symbol': <point_symbol>}]`
The link between PLR and legend entry has to be set up correctly as well of course. Since every PLR delivered by the Extract has its related LegendEntry in place grouping should be possible like it is today already by the type_code.

**Comment by voisardf** [comment]
yes, that is the fastest 'workaround'

**Comment by sitj-marc** [comment]
Hello,
We have also some problems in the KBS data.
For both type of the contaminated military sites (point or polygon), the static PDF is not generated. The system return this message : "IndexError: string index out of range."
The dynamic extract is generated only with point type data. With the polygon type data the system return this message : ' "Could not create geometry because of errors " shapely.errors.WKBReadingError: Could not create geometry because of errors while reading input. '
We have also the same problem and the same error message with the contaminated_public_transport_sites

**Comment by vvmruder** [comment]
@sitj-marc Would it be possible to provide a dump of the schema contaminated_military_sites or contaminated_public_transport_sites. Maybe not here but as Mail? I could have a look than.

@voisardf Do you have some insight of the JU setup? Maybe you can give some more details?

**Comment by sitj-marc** [comment]
Hello,
Thank you for your return. Yes sure I could send you both dump of both schema. On what e-mail address you want me to send them ?

**Comment by voisardf** [comment]
ok. I integrated the contaminated civil aviation sites and contaminated military sites yesterday.
For me, the pdf generation with civil aviation data works, but I only get one legend element in case of multiple geometries for the same typecode on a real estate.

For the contaminated military sites I get the same error than @sitj-marc : 
https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L314
```2022-01-21 08:02:31,105 DEBUG [pyramid_oereb.contrib.print_proxy.mapfish_print.mapfish_print:188][waitress-1] get_wms_url_params() read configuration {'TRANSPARENT': 'true'}

2022-01-21 08:02:31,106 ERROR [waitress:404][waitress-1] Exception while serving /oereb/extract/pdf/

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 13, in _error_handler

    response = request.invoke_exception_view(exc_info)

  File "/usr/local/lib/python3.7/site-packages/pyramid/view.py", line 795, in invoke_exception_view

    raise HTTPNotFound

pyramid.httpexceptions.HTTPNotFound: The resource could not be found.


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/waitress/channel.py", line 397, in service

    task.service()

  File "/usr/local/lib/python3.7/site-packages/waitress/task.py", line 168, in service

    self.execute()

  File "/usr/local/lib/python3.7/site-packages/waitress/task.py", line 434, in execute

    app_iter = self.channel.server.application(environ, start_response)

  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 274, in __call__

    response = self.execution_policy(environ, self)

  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 283, in default_execution_policy

    return request.invoke_exception_view(reraise=True)

  File "/usr/local/lib/python3.7/site-packages/pyramid/view.py", line 794, in invoke_exception_view

    reraise_(*exc_info)

  File "/usr/local/lib/python3.7/site-packages/pyramid/_compat.py", line 179, in reraise

    raise value

  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 281, in default_execution_policy

    return router.invoke_request(request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 249, in invoke_request

    response = handle_request(request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 43, in excview_tween

    response = _error_handler(request, exc)

  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 17, in _error_handler

    reraise(*exc_info)

  File "/usr/local/lib/python3.7/site-packages/pyramid/_compat.py", line 179, in reraise

    raise value

  File "/usr/local/lib/python3.7/site-packages/pyramid/tweens.py", line 41, in excview_tween

    response = handler(request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/router.py", line 148, in handle_request

    registry, request, context, context_iface, view_name

  File "/usr/local/lib/python3.7/site-packages/pyramid/view.py", line 683, in _call_view

    response = view_callable(context, request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/config/views.py", line 188, in attr_view

    return view(context, request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/config/views.py", line 214, in predicate_wrapper

    return view(context, request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 401, in viewresult_to_response

    result = view(context, request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/viewderivers.py", line 116, in _class_requestonly_view

    response = getattr(inst, attr)()

  File "/workspace/pyramid_oereb/core/views/webservice.py", line 309, in get_extract_by_id

    request=self._request

  File "/usr/local/lib/python3.7/site-packages/pyramid/renderers.py", line 138, in render_to_response

    result = helper.render_to_response(value, None, request=request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/renderers.py", line 474, in render_to_response

    result = self.render(value, system_values, request=request)

  File "/usr/local/lib/python3.7/site-packages/pyramid/renderers.py", line 470, in render

    result = renderer(value, system_values)

  File "/workspace/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py", line 86, in __call__

    self.convert_to_printable_extract(extract_as_dict, feature_geometry)

  File "/workspace/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py", line 314, in convert_to_printable_extract

    'layers': params.pop('LAYERS', '')[0].split(','),

IndexError: string index out of range```

WMS would be: https://wms.geo.admin.ch/?service=WMS&version=1.3.0&request=GetMap&layers=ch.vbs.kataster-belasteter-standorte-militaer_v2_0.oereb&style=default&crs=EPSG%3A2056&bbox=2475000%2C1060000%2C2845000%2C1310000&width=740&height=500&format=image%2Fpng&BBOX=2553899.7382210954%2C1202930.321561677%2C2554267.8487789044%2C1203139.3904383231&SRS=EPSG%3A2056&WIDTH=493&HEIGHT=280

**Comment by voisardf** [comment]
I think it's maybe an upper/lowercase issue on the LAYERS parameter - checking it right now

**Comment by voisardf** [comment]
@vvmruder @jwkaltz @MaxHoeferGEOINFO @sitj-marc I can confirm, when changing the **layers** parameter to _uppercase_ in the data, the PDF is produced also for contaminated military sites.
We have to improve the code there to accept either lowercase or uppercase parameters at https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L310-L316

@mki-c2c Are you still on the mapfish_print proxy? could you fix that or shall somebody else handle it?

**Comment by voisardf** [comment]
contaminated military sites - only point data:
[20220121091757_extract.pdf](https://github.com/openoereb/pyramid_oereb/files/7911944/20220121091757_extract.pdf)

contaminated military sites - only surface data:
[20220121092520_extract.pdf](https://github.com/openoereb/pyramid_oereb/files/7912064/20220121092520_extract.pdf)

contaminated civil aviation sites - point and surface data of the same type:
[20220121092002_extract.pdf](https://github.com/openoereb/pyramid_oereb/files/7911960/20220121092002_extract.pdf)

**Comment by mki-c2c** [comment]
hello @voisardf I have finished work on the pdf module, but I can sure make a quick fix on the topic. Is the analysis exhaustive, or may there be further side impacts which have to be checked ?

**Comment by vvmruder** [comment]
We tracked it down with @voisardf to the hook method which gets the legend symbol. I will take care about this.

Conclusion-we have more than one problem:

1. fix hook method for symbol
2. sanitizing of lower/upper case in print proxy
3. possibly need to fix legend entry collection in print proxy. Legend entries might have the same type code but a different ID. So selection by type code is not enough any more.

**Comment by mki-c2c** [comment]
I could make a quick fix (with unit test) for item 2, so the pdf generation get's to work.
And we can address 1. and 3. later on.
Is that OK for you ?

**Comment by vvmruder** [comment]
@mki-c2c ok for me. Do we create on pull request or should I split this into separate issues?

**Comment by vvmruder** [comment]
@mki-c2c I split them into 3 new issues. I think its more easy to keep track. Ok?

**Comment by mki-c2c** [comment]
great. I did the uppercase one, checking the other ones at some other moment

**Comment by voisardf** [comment]
thanks for the fix https://github.com/openoereb/pyramid_oereb/issues/1475! Checked it with contaminated military sites and now it's working either way
