### ISSUE TITLE
sanitizing of lower/upper case in print proxy

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#1475]
We tracked it down with @voisardf to the hook method which gets the legend symbol. I will take care about this.

Conclusion-we have more than one problem:

1. fix hook method for symbol
2. sanitizing of lower/upper case in print proxy
3. possibly need to fix legend entry collection in print proxy. Legend entries might have the same type code but a different ID. So selection by type code is not enough any more.

_Originally posted by @vvmruder in https://github.com/openoereb/pyramid_oereb/issues/1463#issuecomment-1018354643_

**Comment by mki-c2c** [comment]
partial fix should be in #1478
