### ISSUE TITLE
otherLegend missing in extract with subthemes

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#1481]
For a plr with a subtheme the otherLegends are missing in both the xml and the json extract:

<img width="304" alt="no_otherlegend" src="https://user-images.githubusercontent.com/3659322/151379152-7892983e-d228-4fa8-88c7-e65304bc080f.png">

I made a quick crosscheck and deleted the value in `legend_entry.sub_theme` for this plr and the otherLegends now appear in the json:

<img width="266" alt="with_otherlegend" src="https://user-images.githubusercontent.com/3659322/151379719-b42a5eed-d52f-443f-9bb2-e60116077835.png">

**Comment by vvmruder** [comment]
@peterschaer after merging #1482 this might be solved. Can you check the status?

**Comment by peterschaer** [comment]
Looks good to me, other legends are back in JSON, XML and PDF. Thanks!
