### ISSUE TITLE
Stats views are empty

### ISSUE THREAD

**Issue by lopo977** [openoereb/pyramid_oereb#1516]
Hi everybody.

We are using in Ticino waitress also in production.
The new codebase produces JSON w/ "extras": null in logs table.msg, maybe because in webservice.py, the statements like
`# response.extras = OerebStats(service='GetEGRID', output_format=output_format) `
are commented, etc.

Due to this, the stats views are always empty
![immagine](https://user-images.githubusercontent.com/26254706/154936999-34069f32-8b86-480d-ac57-9559c2ab6d0d.png)

because they are parsing the response.extras "service" field as you can see in DDL:

...
```
   FROM logs
  WHERE logs.logger::text = 'JSON'::text AND (((logs.msg::json -> 'response'::text) -> 'extras'::text) ->> 'service'::text) = 'GetExtractById'::text;
```
...

Is it possible to fix this @jwkaltz ?
Thank you in advance.

**Comment by jwkaltz** [comment]
Thanks for the report @lopo977 , we will investigate.

P.S. please don't directly assign individual people to the issues, we need to do a triage and organize who does what.

**Comment by lopo977** [comment]
> 

@jwkaltz I am sorry. I will not assign the issues directly in the future.

**Comment by jwkaltz** [comment]
Hi @lopo977 , this should now be fixed in https://pypi.org/project/pyramid-oereb/2.0.0rc2/ , can you please try?

**Comment by lopo977** [comment]
Thank you @jwkaltz. I have just tested. It works as expected.
