### ISSUE TITLE
c2wsgiutils requirement not precise enough?

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#1521]
In requirements.txt the library c2cwsgiutils requires version 3.*
https://github.com/openoereb/pyramid_oereb/blob/2a2ef0c822495f74b0691c0b886ff13d4f5f4621/requirements.txt#L16

But the sqlalchemylogger module was only introduced in 3.9.0. So it may be possible to get a version of c2cwsgiutils without sqlalchemylogger. Should the requirement not be upgraded to at least 3.9.*?

**Comment by mki-c2c** [comment]
closed by https://github.com/openoereb/pyramid_oereb/pull/1531
requirement is now 5.*
