### ISSUE TITLE
'DatabaseSource' object has no attribute '_theme_record'

### ISSUE THREAD

**Issue by lopo977** [openoereb/pyramid_oereb#1532]
![immagine](https://user-images.githubusercontent.com/26254706/158365384-4cc0320e-0c68-4265-b17c-8d0fe74a7f46.png)

in statement 
        # Add empty record if topic is not available
        else:
            self.records = [EmptyPlrRecord(self._theme_record, has_data=False)]

https://github.com/openoereb/pyramid_oereb/blob/ce8b5cf3901b9324bb56a13ed49831e134c39278/pyramid_oereb/contrib/data_sources/interlis_2_3/sources/plr.py#L566

**Comment by vvmruder** [comment]
Probably fixed by the same solution of the parent PLR-Class: https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/contrib/data_sources/standard/sources/plr.py#L543-L547

Should be implemented with a instance function, so it can be called and to avoid copy&paste code...

**Comment by marionb** [comment]
@lopo977 can you test with this PR #1538 if it is working?

**Comment by lopo977** [comment]
I have tested. It is working.
