### ISSUE TITLE
promote extract_index in dynamic extract (XML/JSON)

### ISSUE THREAD

**Issue by lopo977** [openoereb/pyramid_oereb#1553]
In order to have the same sorting of themes and subthemes in the web viewer, it would be desirable to have the extract_index field of the theme table available in the dynamic json and xml extract. This is for themes and subthemes.

![immagine](https://user-images.githubusercontent.com/26254706/165237394-d25b4b8d-adb2-484e-866a-ebeca66f2bba.png)

Thank you in advance.

**Comment by voisardf** [comment]
@lopo977 : As discussed at the user group meeting, the order in which the themes/subthemes are written in the XML/JSON should already respect the extract_index.
Before we can decide to add this attribute to the JSON, we need to discuss the question with swisstopo. As the JSON is an optional format it might be possible to add it their. On the other hand we should be careful if we introduce divergences between the XML and the JSON specs.

**Comment by lopo977** [comment]
@voisardf the order in which the themes and subthemes respects the extract_index, according to our testers.Thank you. Issue can be closed.

**Comment by voisardf** [comment]
Ok, thanks for the feedback. I'm closing the issue.
