### ISSUE TITLE
Field "Stand der amtlichen Vermessung"

### ISSUE THREAD

**Issue by sasentom** [openoereb/pyramid_oereb#1554]
It concerns the field "Stand der amtlichen Vermessung", on page 11 of the instruction "ÖREB-Kataster: Inhalt und Darstellung des statischen Auszugs". This is a mandatory field on the static extract. For information purposes, it also appears on several cantonal ÖREB-Viewers. It is therefore information that, from our point of view, it would make sense to introduce and manage in the ÖREB-DB, ideally as an additional field in pyramid_oereb_main.real_estate. Canton Ticino has implemented it this way, using a custom solution. Can it be promoted to a standard solution?

**Comment by jwkaltz** [comment]
In the current standard, the idea is to use a hook method and configure it here:
"https://github.com/openoereb/pyramid_oereb/blob/6341b9a37a175b50b02d7f7e602f031a19ed5159/dev/config/pyramid_oereb.yml.mako#L566"
The default implementation is here https://github.com/openoereb/pyramid_oereb/blob/6341b9a37a175b50b02d7f7e602f031a19ed5159/pyramid_oereb/core/hook_methods.py#L64

Is this how you have currently implemented it?
In theory yes, the default implementation could be adapted to read from the database, or, an additional standard implementation can be used to the core to read from the database, this would however require extending the tests as well.

**Comment by lopo977** [comment]
Thank you, @jwkaltz for your quick answer.
I have another question, just to clarify.

We have seen there's a hook method to perform the task.
Current implementation is:

update_date = datetime.datetime.now()

Is this a stub implementation or for all the other cantons is it correct to have 'datetime.datetime.now()' as the last update date of der amtlichen Vermessung?

Thank you in advance.
L.

**Comment by lopo977** [comment]
I refactored our code according to the object model.

I will implement a strategy pattern, in order to select the 'tessin' implementation.
Thank you so much @jwkaltz.

**Comment by lopo977** [comment]
Thank you all.
