### ISSUE TITLE
create_theme_tables does not work

### ISSUE THREAD

**Issue by CoNussberger** [openoereb/pyramid_oereb#1562]
create_theme_tables does not work.
Error is: 
Traceback (most recent call last):
  File ".venv/bin/create_theme_tables", line 33, in <module>
    sys.exit(load_entry_point('oereb-server-gr', 'console_scripts', 'create_theme_tables')())
  File "/home/apache2/oereb_server_gr/.venv/lib/python3.7/site-packages/pyramid_oereb/contrib/data_sources/create_tables.py", line 213, in create_theme_tables
    sql_file=sql_file
TypeError: create_theme_tables_() missing 1 required positional argument: 'source_class'

**Comment by jwkaltz** [comment]
@CoNussberger I think this might be solved in the open PR #1547 
Could you test that PR?

**Comment by svamaa** [comment]
I get the same error. The parameter list is not complete [here](https://github.com/openoereb/pyramid_oereb/blob/86c166e7c36f0f244f339bfb64c5a1e1e2a1ea10/pyramid_oereb/contrib/data_sources/create_tables.py#L261)
But is this function still relevant? As far as I see, it is only used from command line and the local oereb-db is filled differently.
