### ISSUE TITLE
local tests failure when DB not ready

### ISSUE THREAD

**Issue by mki-c2c** [openoereb/pyramid_oereb#1570]
I was having some problems when running local tests with `make docker-tests`. Once in a while startup of pytest is so fast that the postgres DB container is not ready yet and cannot accept connections. Usually the next test run will work fine.

An explicit wait condition should be put in the docker composition (or in the test Makefile) so that tests can only start when the DB is ready.

Idea: check if the docker-compose healthcheck can be used like described here:
https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y

**Comment by vvmruder** [comment]
@mki-c2c I assume you run the make directly on you machine and not in docker?

**Comment by mki-c2c** [comment]
the command `make docker-tests` is launched directly on the computer. As the recipe name suggests, it then spawns a docker composition. So the DB runs in a docker container and not on the machine (unlike the CI tests where the DB runs as an independent service)

**Comment by vvmruder** [comment]
Sorry-now I saw `make docker-tests` :)

I will have a look at this one

**Comment by vvmruder** [comment]
@vvmruder recheck

**Comment by jwkaltz** [comment]
Can not be reproduced
