### ISSUE TITLE
Classification of restrictions in the table of contents and down in the pages of the static extract (PDF)

### ISSUE THREAD

**Issue by sitj-marc** [openoereb/pyramid_oereb#1600]
Hello,
A restriction when it's "In Force" and "With or Without Pre-effects" at the same time, is not classified as it's mentionned in the instruction "Weisung «ÖREB-Kataster: Inhalt und Darstellung des statischen Auszugs»".
The Law_status of "Without Pre-Effects" comes before the "In Force".

Thank you in advance for your answers.

![Classification_issue](https://user-images.githubusercontent.com/3088758/184321826-b86d0579-5803-4b93-bb27-0665e38cabe2.png)

**Comment by voisardf** [comment]
@michmuel @svamaa @peterschaer @ralphschulerSZ @MaxHoeferGEOINFO @marionb Has anybody already data with status  inKraft and mit/ohneVorwirkung and experienced issues with the order of the table of content?
Maybe it's an issue in french? I'll try to test it, but I do not have data ready yet for it.

**Comment by michmuel** [comment]
We have not yet PLRs "laufendeAenderungen" in BL.

**Comment by peterschaer** [comment]
In Bern, we don't have any ongoing changes yet either. However, I am in the process of integrating the test data set `Sicherheitszonenplan`. I have manipulated the data in such a way that on one parcel there is both `inKraft` and `AenderungMitVorwirkung`. In the PDF it looks like this:

German:
![de](https://user-images.githubusercontent.com/3659322/186871695-e1aa534c-8153-4ba1-9d9d-92bd286a37ff.PNG)


French:
![fr](https://user-images.githubusercontent.com/3659322/186871716-a1d04fd0-7530-4f25-ae6b-74edffb96f6b.PNG)

This is the order as defined in the directive. This looks good to me.
We use pyramid_oereb v2.2.3 and pyramid_oereb_mfp up to and including commit [ea46791](https://github.com/openoereb/pyramid_oereb_mfp/commit/ea46791add2b953de69c4bbd129dbbe019731bc9).

**Comment by sitj-marc** [comment]
Thank you all for your feedbacks. We use also pyramid_oereb v2.2.3 but we didn't include yet the QR-code.

The same order of classification appears also in the json extract :

![image](https://user-images.githubusercontent.com/3088758/186882612-5a816d67-1ba8-40e3-a3d7-13cfef3522da.png)

I did the same thing like Peter and in this case the order is correct : 

![image](https://user-images.githubusercontent.com/3088758/186883781-07e9015c-d429-42b2-a0da-584c2b7a63f4.png)

**Comment by voisardf** [comment]
So in conclusion, the order is correct if it's a federal data set, but not a cantonal. I will try to verify this soon

**Comment by svamaa** [comment]
Indeed, we have had the issue in BS as well and fixed it with overwriting the hook method plr_sort_within_themes:
[plr_sort_within_themes](https://github.com/openoereb/pyramid_oereb/blob/526dcb222088526e62d622f08ddf037cd2c7a917/pyramid_oereb/core/hook_methods.py#L127)

I can create a pull request with the fix we've implemented?

**Comment by voisardf** [comment]
@svamaa That would be perfect, thanks a lot! :)

**Comment by voisardf** [comment]
@sitj-marc Should be fixed with this PR https://github.com/openoereb/pyramid_oereb/pull/1607 Maybe you could also test and confirm it?

**Comment by voisardf** [comment]
@sitj-marc Perfect, thanks for the feedback!
