### ISSUE TITLE
XML conformity with QR Code and SubunitOfLandRegister

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb#1601]
Hi all

The canton SG activated the QR code and the subunit of landregisters for their new pyramid_oereb version. 
Now the XML conformity check runs into the following errors: 

![image](https://user-images.githubusercontent.com/54711581/184869537-10a0e885-4863-4c12-a9e6-2ce00494fce8.png)

The order should be different, is that correct? 
Is that something which could be fixed? It's not very time critical from my point of view, since the information is included correctly, just in a different order.

Thanks & Regards
Max

**Comment by svamaa** [comment]
Hi Max
this bug will be fixed within this pull request: https://github.com/openoereb/pyramid_oereb/pull/1606

**Comment by MaxHoeferGEOINFO** [comment]
Hi Anne
thanks :) 
Cheers
Max
