### ISSUE TITLE
OerebLex Prebublinks

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb#1617]
We use OerebLex in BL and will use the OerebLex-"Prepub-Module" for managing the "Laufende Aenderungen". The "prepublinks"-xml differs a bit from the "geolinks"-xml by the attributes of the element "document" (if attribute doctype="prepublication": additional attributes "status", "status_start_date", "status_end_date" but without attributes "municipality", "category", "enactment_date", "abrogation_date", "decree_date").

The mapping of the lexlink information to the document record has to be refined (https://github.com/openoereb/pyramid_oereb/blob/85f816b706376319f54c47d58c4b3dca84436112/pyramid_oereb/contrib/data_sources/oereblex/sources/document.py#L141). There are also changes required in the geolink_formatter.

I can provide these changes but have to know if someone else is using the OerebLex-Prepub-Module for the "Laufende Aenderungen" to see what are the requirements for a standard mapping.

**Comment by thomasmarti** [comment]
Hi @michmuel
We are also interested in using prebubs. I've tried this just today and got the following error.
Is this the one you'd like to address with this issue?

` documents = self._parser.from_url(url, request_params, proxies=self._proxies, auth=self._auth)

  File "/usr/local/lib/python3.9/site-packages/geolink_formatter/parser.py", line 182, in from_url
    return self.from_string(response.content)
  File "/usr/local/lib/python3.9/site-packages/geolink_formatter/parser.py", line 106, in from_string
    root = self._parse_xml(xml)

  File "/usr/local/lib/python3.9/site-packages/geolink_formatter/parser.py", line 83, in _parse_xml
    self._schema.assertValid(content)
	
  File "src/lxml/etree.pyx", line 3640, in lxml.etree._Validator.assertValid
lxml.etree.DocumentInvalid: Element 'prepublinks': No matching global declaration available for the validation root., line 2`

**Comment by thomasmarti** [comment]
Here is a sample prepub-Link:

https://oereblex.ag.ch/api/prepubs/4504.xml

**Comment by michmuel** [comment]
Yes. There are two issues:

First, the xml provided by the prepublink is not valid against the xml schema definition used by the xml format check routine of the geolink_formatter. This causes the error indicated in your post.

Second, the document element in the prepublink does not provide all the attributes expected by the OerebLex source of pyramid_oereb. E.G. there is no attribute "enactment_date" but an attribute "status_start_date". Another question is if the attribute "status" should be used for generating the document title.

I think pyramid oereb should be able to process prepublinks in a general way. More elaborated cantonal rules would require to write and use individual functions.

**Comment by michmuel** [comment]
Changes in oereblex source implemented. Handling of prepublinks is possible now.
