### ISSUE TITLE
Reduce Requests to print server for each PDF request

### ISSUE THREAD

**Issue by svamaa** [openoereb/pyramid_oereb#1623]
When requesting a pdf extract with pyramid_oereb, 2 requests to the print server are done.
One for the [request itself ](https://github.com/openoereb/pyramid_oereb/blob/3636d915b59a40066ac4ac564654dfe4029195d9/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L116) and one to [determine the number of pages used for table of contents](https://github.com/openoereb/pyramid_oereb/blob/3636d915b59a40066ac4ac564654dfe4029195d9/pyramid_oereb/contrib/print_proxy/mapfish_print/mapfish_print.py#L137)

Is there a possibility to omit the second request and reduce network traffic and ressources?

**Comment by jwkaltz** [comment]
This is configurable via this option:
https://github.com/openoereb/pyramid_oereb/blob/bd4d87867fe8d5fa75795486e65ba0e9dadac41d/dev/config/pyramid_oereb.yml.mako#L99-L104

**Comment by jwkaltz** [comment]
@svamaa I think the previous comment answers your question, so I am closing this issue.
