### ISSUE TITLE
Python 3.7 end of support in June 2023

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#1627]
Python 3.7 will be end of life in June 2023 (no more security updates).

pyramid_oereb users should switch to Python 3.8 at the least.

I recommend we 
* remove Python 3.7 support in pyramid_oereb now (or soon), 
* set 3.11 as development version -> #1633 
* update flake related libraries accordingly.

Any other opinions? ping @svamaa @vvmruder @voisardf

**Comment by voisardf** [comment]
For us this is ok, but I think we should ask the members to make sure it's ok for all

**Comment by peterschaer** [comment]
We're on Python 3.9, so we no longer need Python 3.7 support.

**Comment by svamaa** [comment]
We're also on 3.9 in BS

**Comment by jwkaltz** [comment]
As an intermediary step, I propose to simply remove from python 3.7 from the list of officially supported Python versions, and recommend Python 3.8 for now, which everybody should have. We can discuss moving to Python 3.11 as recommended version at a later time.
Switching to Python 3.8 is a must for security reasons and will also allow us the finalize the updates of deprecated libraries.
