### ISSUE TITLE
Documentation: fix warnings

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#1675]
Documentation generation (with `make doc-html`) has 135 warnings which should be addressed.

Many seem related to wrong type references, for example
`/home/wkaltz/src/oereb/pyramid_oereb/pyramid_oereb/core/readers/law_status.py:docstring of pyramid_oereb.core.readers.law_status.LawStatusReader:1: WARNING: undefined label: 'api-pyramid_oereb-core-records-lawstatus-lawstatusrecord'
/home/wkaltz/src/oereb/pyramid_oereb/pyramid_oereb/core/readers/real_estate_type.py:docstring of pyramid_oereb.core.readers.real_estate_type.RealEstateTypeReader.__init__:1: WARNING: undefined label: 'api-pyramid_oereb-core-sources-realestatetype-realestatetypebasesource'
/home/wkaltz/src/oereb/pyramid_oereb/pyramid_oereb/core/readers/real_estate_type.py:docstring of pyramid_oereb.core.readers.real_estate_type.RealEstateTypeReader:1: WARNING: undefined label: 'api-pyramid_oereb-core-records-realestatetype-realestatetyperecord'
`

**Comment by svamaa** [comment]
#1257

**Comment by julianhafner** [comment]
@voisardf @vvmruder has work already been done on this issue? I had a look on the warnings and could prepare a PR.

**Comment by vvmruder** [comment]
@julianhafner Yes. Its in progress. Iam on it. Will provide a PR soon. Need to rebase on last recent changes :)
