### ISSUE TITLE
Hook method for ReferenceWMS

### ISSUE THREAD

**Issue by svamaa** [openoereb/pyramid_oereb#1771]
When creating an oereb extract, the referencewms URL is an essential attribute.

In BS we'd like to have an additional hook method, such as the logoRef and symbolRef hook methods in order to be able to configure at extract creation which url to use as referencewms.

We've fixed the issue recently for the logoref and qr-code. Referencewms is the last URL that should be configurable via a hook method.

**Comment by michmuel** [comment]
I guess that is feasible. That would be one hook per theme, right?

**Comment by michmuel** [comment]
However, as a theme can have several view services hooks for wms are likely a bit more complex than for symbols.

**Comment by svamaa** [comment]
can be reopened if needed. Requirement is too low implement.
