### ISSUE TITLE
swisstopo address source: add timeout?

### ISSUE THREAD

**Issue by michmuel** [openoereb/pyramid_oereb#1875]
Shall we introduce a timeout at https://github.com/openoereb/pyramid_oereb/blob/1a3ba4bc9010d479473d5d88b00e31bab5ac1e7e/pyramid_oereb/contrib/data_sources/swisstopo/address.py#L64 ?

**Comment by voisardf** [comment]
@michmuel personally I would go for an slightly higher value - maybe 5s?

**Comment by vvmruder** [comment]
3s is enaough I would say. Otherwise we could make it configurable.
