### ISSUE TITLE
TOC - fixed TOC pages in configuraiton

### ISSUE THREAD

**Issue by svamaa** [openoereb/pyramid_oereb#2039]
currently, the exact number of TOC pages has to be calculate which has effects on the performance of the pdf extract.
As most of the cantons have the same number of TOC pages for a majority of extracts, we will add a new configuration option that allows to set a default number of TOC pages other than one. thus each canton can choose between the calculated value or define the default value which works for 99% of the extracts gaining in performance.

**Comment by voisardf** [comment]
fixed by https://github.com/openoereb/pyramid_oereb/pull/2042
