### ISSUE TITLE
Remove unused code for complete PDF extract

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#364]
It's planned to remove the complete PDF extract as mandatory result from the law regarding the PLR cataster.
So it would be a good idea to remove this code in the mapfish_print_proxy renderer.

**Comment by vvmruder** [comment]
can this issue be closed?

**Comment by voisardf** [comment]
nope, still to be done, sorry

**Comment by vvmruder** [comment]
@voisardf Can please be more specific on what should be removed?

**Comment by voisardf** [comment]
basically we could remove https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L98-L124 probably L69 too. And there might be some possible cleanup in the Jasper templates as followup

But before we do that, we need to make sure, that a complete static extract is neither a need nor a nice to have anymore! :)

**Comment by jwkaltz** [comment]
@voisardf I have seen your comment in another issue (https://github.com/openoereb/pyramid_oereb/issues/766#issuecomment-459336472) , which makes me feel that we should in fact not do this issue here (remove implementation of "full" pdf extract).
Can you confirm? 
FYI @vvmruder

**Comment by voisardf** [comment]
Thanks @jwkaltz : Yes indeed, for now, we should not remove the code to produce a full extract. I suggest, I contact the federal authority to get an decision if we can or not remove this option.
Is that ok for you?

**Comment by jwkaltz** [comment]
Yes, thanks in advance @voisardf . Ideally, something to confirm / non confirm at the upcoming user group, so that everybody is up to date on this subject.

**Comment by jwkaltz** [comment]
Until further notice, the "full" flavour will remain available.
