### ISSUE TITLE
Mapfish Print: Sorting of legend

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#380]
The legend in static extract should be sorted like follows:
1. subtheme
2. geometry_type
3. part_in_percent

**Comment by jwkaltz** [comment]
@vvmruder the part "Plus: static forrest borders are presented after noise sensitivity level zones." is a different issue (that is now resolved), right? So we can remove this from this issue in good conscience?

**Comment by vvmruder** [comment]
👍 I updated the text
