### ISSUE TITLE
JSON validation not reliable

### ISSUE THREAD

**Issue by kdeininger** [openoereb/pyramid_oereb#44]
The validation of a returned JSON from the webservice against its schema always succeeds, even if it contains obvious errors.

The python package [jsonschema](https://pypi.python.org/pypi/jsonschema) is used for validation. The same behavior can be reproduced with the online validator on https://json-schema-validator.herokuapp.com/. It seems to be related to the property "anyOf" within the root object.

Is it caused by a bug in the validators or an error in the schema?

**Comment by jwkaltz** [comment]
@kdeininger when I validate an example extract (from schwyz's installation) against the schema http://schemas.geo.admin.ch/V_D/OeREB/1.0/extractdata.json within the online tool https://json-schema-validator.herokuapp.com/
it says "Validation results: success"

So this issue is solved now - or is this not the right test?

**Comment by kdeininger** [comment]
This is an old issue. We use the JSON validator of the package `jsonschema` in the tests to validate the webservice output against the schema:
https://github.com/camptocamp/pyramid_oereb/blob/c5af801696dda82fa399cd6ecc855952b8526ca5/tests/webservice/test_getextractbyid.py#L191
We noticed that the validation always succeeded, even with obvious errors in the response. I think this behavior has been related to errors in the schema itself.

To be sure, we should run some additional tests with the current schema and different malformed responses.

**Comment by kdeininger** [comment]
I still think this issue is caused by the extract schema. I have tested the validator with another schema we use and the validation works fine, e.g. detecting invalid attributes and types.

**Comment by vvmruder** [comment]
Should we close this? As far as I know the JSON schema is not longer "supported" by ÖREB. It is a now a optional member...
