### ISSUE TITLE
optimize implementation sorting of themes for toc

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#443]
Currently, when the themes are separated into concerned_theme and not_concerned_theme lists, they do keep their relative sorting order within these lists. But the overall sorting order of all themes as defined in the configuration is then no longer directly known. When a theme has to get moved from concerned_theme to not_concerned_theme, we can not easily know in which place of the list to put it.

In https://github.com/camptocamp/pyramid_oereb/pull/429, a sorting "from scratch" has been implemented, to resort the not_concerned_theme in the right order. But this code could be more efficient and clearer if we keep more knowledge about the original sort order somewhere in the data structures.

**Comment by vvmruder** [comment]
Just an addition on this: I think we can already clarify that we need a sort attribute on the Theme object. So we can use this later easily for sorting algorithm because every PLR object has the corresponding Theme object as related object.
