### ISSUE TITLE
File in Document not rendered

### ISSUE THREAD

**Issue by ger-benjamin** [openoereb/pyramid_oereb#611]
In the extract JSON was this TODO:

It was removed with PR #612 

In the specification (Rahmenmodell) there is sometimes mention of this File in a Document. And all except the renderer look to support this File (https://github.com/camptocamp/pyramid_oereb/blob/1a61615b2e418e45167939b6501c496dd660d2d7/pyramid_oereb/lib/records/documents.py#L152) 

But, there is never mention of the Extract or ExtractData (you can take a look at  https://github.com/camptocamp/pyramid_oereb/tree/1a61615b2e418e45167939b6501c496dd660d2d7/tests/resources/schema/20170825)

So what should we do ? Should the File be rendered in any cases ?

**Comment by jwkaltz** [comment]
After discussion, the original TODO was obsolete (the full flavour is currently functioning)
