### ISSUE TITLE
Multiple responsible office not rendered correctly

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#651]
We saw a strange issue on responsible office per theme page. It is not correctly shown in PDF. It is possible that we have several, responsible offices per theme. In the moment it is concatenated in a strange way as you can see in this PDF on page 4
[PDF-Auszug-Augst_235_DiP.pdf](https://github.com/camptocamp/pyramid_oereb/files/2371399/PDF-Auszug-Augst_235_DiP.pdf)

A more detailed look on the PDF call with getspec parameter points out that name and Office at web is joined for the values by a `\n`...
![auswahl_058](https://user-images.githubusercontent.com/3714179/45367761-48000f80-b5e2-11e8-9db6-2411e26873e6.png)

This is not correct. Responsible office should be an array of elements with *Name* and *OfficeAtWeb* attributes. As far as I understood the concatination happens inside the MapFishPrint Proxy:
https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L341

I expect per responsible office an entry in PDF with name as title followed by URL.

My problem is, that I do not understand the logic of this... Maybe someone can support me here? @ger-benjamin or @jwkaltz or @voisardf ?

**Comment by ger-benjamin** [comment]
We currently "flatten" object for responsibleOffice. If you remove these both lines:
- https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L205
 - https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L33 (I currently don't really understand why I've to remove this one).

You'll get an object like that:
```
                "ResponsibleOffice": {
                    "Name": [
                        {
                            "Language": "de",
                            "Text": "Bundesamt f\u00fcr Verkehr BAV"
                        }
                    ],
                    "OfficeAtWeb": "http://www.bav.admin.ch/themen/verkehrspolitik/00709/index.html"
                },
```

(Then, we can also remove ResponsibleOffice_name and ResponsibleOffice_OfficeAtWeb here: https://github.com/camptocamp/pyramid_oereb/blob/master/pyramid_oereb/contrib/print_proxy/mapfish_print.py#L275-L277) (this array is used to add this `\n`)
And perhaps some other cleaning....

Then we also have to adapt the jrxml templates

My current problem is that I don't have access to a multiple offices case.... So I just can suppose what we have to do. I can add one of these cases, but sadly not this week :-/

**Comment by vvmruder** [comment]
Thanks. I will have detailed look at it.

**Comment by StefanKiener** [comment]
The canton Aargau is affected by the problem and we hoped to get the bugfix with version 1.3
We strongly ask you to integrate the bugfix in the next version. Thank you

**Comment by jwkaltz** [comment]
JSON-request for the example provided in the original comment:
https://geoview.bl.ch/main/oereb/extract/reduced/json/CH887417597077
