### ISSUE TITLE
Projected real estates

### ISSUE THREAD

**Issue by svareg** [openoereb/pyramid_oereb#679]
In Basel-Stadt, we would like to generate reports for projected real estates.
But for now, this is not possible if the projected real estate keep the same EGRID-Number as the "legal" one. 

Because the real estates are uniquely identified by EGRID-Number, we cannot have twice the same EGRID-Number, even if on is "legal" and the other one is "projected".

It seems that no other canton has the same interest at the moment. 
But I think this can be an intereting future feature, and the needs can be discussed here.

It would be interesting as well for me to know if others keep the "legal" EGRID-Number on projected real estates.

For ease of reference, the protocol of the User-Group for this discussion:
- nobody else had the idea to use this right in the moment
- Andreas Neumann, Clemens Rudert see the advantage fur the end user
- questions about the legal consequences if projected information is provided
- topic will stay open
- François Voisard will push discussion about this on ÖEREB day (13.11.2018)
- Guillaume Remy will file an issue on githab to collect all discussion and information

**Comment by svareg** [comment]
As additional information, here is the answer we got from swisstopo about this subject:

> Das Problem kommt aus der AV, sprich ist im DM.01 nicht gelöst. Dort kann derselbe EGRID sowohl in der Tabelle «Grundstück» wie auch in der Tabelle «proj. Grundstück» vorkommen. Ob das dem Willen des Urhebers des EGRID’s, sprich dem EGBA, entspricht, ist gesondert zu klären und braucht Zeit.
> (...)
> Da im ÖREB-Kataster vorwiegend der rechtsgültige Stand ausgegeben wird (sowohl ÖREB wie auch AV), hat sich die Arbeitsgruppe mit diesem Thema bisher nicht ausdrücklich auseinandergesetzt. Wie andere Kantone mit diesem Problem umgehen, ist uns nicht bekannt. Es war bisher noch kein Thema bei uns. Swisstopo wird das Problem erst nach der Verabschiedung der Revision der ÖREBKV angehen.

**Comment by svamaa** [comment]
projected real estates are being discussed at swisstopo. We'll wait with further processing until requirements are defined.
