### ISSUE TITLE
map.legendatweb (view_service.legend_at_web) not multilingual

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#704]
`map.legendatweb` supports only a single link. this single link is used in all the languages the extract can be produced in. if we define a link to a german legend this link is also displayed in a french extract.

![legendatweb](https://user-images.githubusercontent.com/3659322/48470834-d49d9880-e7f2-11e8-9889-acd3e145e9f6.PNG)

I know that in the _weisung_ this information is not multilingual. Therefore pyramid_oereb is compliant. But in multilingual cases an extension of this behaviour would be valuable.

**Comment by vvmruder** [comment]
This breaks the actual federal specification of DataExtract. Thats why we need first the OK from federal offices to update specification. After this we can update behaviour.

Somebody does have other suggestions?

**Comment by vvmruder** [comment]
After thinking a little about that, it would be possible to change only the behaviour in the standard DB scheme for this attribute to be multilingual and deliver the result in DataExtract as today. So we 'shadow' the behaviour and are free to adapt to the maybe new specification somewhere in the future...

**Comment by pfirpfel** [comment]
Implemented with  #739
