### ISSUE TITLE
restrictiononlandownership.subtheme not multilingual

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#705]
`restrictiononlandownership.subtheme` (rsp. `public_law_restriction.sub_theme`) is not multilingual.

I know that in the weisung this information is not multilingual. Therefore pyramid_oereb is compliant. But in multilingual cases an extension of this behaviour would be valuable. Especially when #372 will be implemented, subtheme-titles will be printed in pdf extract. In this case those subtheme-titles should be multilingual.

**Comment by vvmruder** [comment]
This breaks the actual federal specification of DataExtract. Thats why we need first the OK from federal offices to update specification. After this we can update behaviour.

Somebody does have other suggestions?

**Comment by vvmruder** [comment]
After thinking a little about that, it would be possible to change only the behaviour in the standard DB scheme for this attribute to be multilingual and deliver the result in DataExtract as today. So we 'shadow' the behaviour and are free to adapt to the maybe new specification somewhere in the future...

**Comment by pfirpfel** [comment]
@peterschaer Is the `sub_theme` property of the legend entry related to the same property of the public_law_restriction? I think they are, but I'm not certain.

**Comment by peterschaer** [comment]
In my opinion they are the same.

**Comment by jwkaltz** [comment]
Implemented in #783
