### ISSUE TITLE
vertical spacing too small between exclusion of liabilities in PDF extract

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#707]
In case of multiple exclusion of liabilities the vertical spacing between the text and the next title is too small

![vorbehalt](https://user-images.githubusercontent.com/3659322/48472312-504d1480-e7f6-11e8-972b-9bbfedbfde94.PNG)

**Comment by vvmruder** [comment]
should be fixed

**Comment by peterschaer** [comment]
Has been fixed in #842
