### ISSUE TITLE
plr_cadastre_authority is printed on multiple lines in PDF extract

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#709]
plr_cadastre_authority is printed on multiple lines in PDF extract. In the _weisung_ this information is printed on one single line.

![kvs](https://user-images.githubusercontent.com/3659322/48472742-36f89800-e7f7-11e8-9b2a-94bc728b4774.PNG)

**Comment by vvmruder** [comment]
BL was accepted by federal office test with this behaviour without problem.

@others: Someone wants to rely directly to the specification or is this style ok?

**Comment by peterschaer** [comment]
For me this is ok  I just wanted to mention it.
