### ISSUE TITLE
TOC wrong if ToC page longer than one page

### ISSUE THREAD

**Issue by pfirpfel** [openoereb/pyramid_oereb#716]
ToC page wraps onto a second page -> all page numbers in the table of contents are off by one.

Example:
[TOC-bug-example.pdf](https://github.com/camptocamp/pyramid_oereb/files/2639513/TOC-bug-example.pdf)

**Comment by pfirpfel** [comment]
@lopo977 FYI:
I analysed the issue:  
To fix the page numbers in the table of content, we would have to merge and rework the affected templates [toc.jrxml](https://github.com/openoereb/pyramid_oereb/blob/master/print/print-apps/oereb/toc.jrxml) and [toc2.jrxml](https://github.com/openoereb/pyramid_oereb/blob/master/print/print-apps/oereb/toc2.jrxml). toc2 (which renders the list of pages) can otherwise not determine, how many pages its parent page is using.

The issue does not look trivial. I have to see next week, when and how we can fix it.

**Comment by lopo977** [comment]
Thank you for the info @pfirpfel

**Comment by sbuettler** [comment]
**New bugs in the newest version of the print-template:**
The page numbers aren't printed anymore on the restriction pages. If the TOC is divided on 2 pages the page numbers aren't anymore visible on the restriction pages except the last page (abbreviation). See example extract: 
[CH210788028837_extract.pdf](https://github.com/openoereb/pyramid_oereb/files/2960766/CH210788028837_extract.pdf)

**Comment by lopo977** [comment]
This commit 
https://github.com/openoereb/pyramid_oereb/commit/de4df0fbbcfb87c8c8e9820e45c1b68d2a8d2fa8#diff-515ee9e319a011ad4220656fc97ffdbe

hides the page numbers shown by @sbuettler 

FROM camptocamp/mapfish_print:3.10.8 works well
FROM camptocamp/mapfish_print:3.18.2 not anymore

**Comment by jwkaltz** [comment]
@lopo977 @sbuettler thanks for the information regarding the disappearing page numbers in MapFish Print 3.18. I have now created a separate issue #813 for this, because it is not related to the TOC problematic in this issue here.

**Comment by jwkaltz** [comment]
Fixed in #859
