### ISSUE TITLE
Static Extract: Remove line breaks in Table 'Übersicht ÖREB-Themen'

### ISSUE THREAD

**Issue by thomasmarti** [openoereb/pyramid_oereb#766]
On page 2 of the static extract there are 3 sections for the overview of OREB topics.
The first section contains topics by which the parcel is affected. The topic name does not fill the whole width of the table. On the right side there is an area for appendencies (TOC_APPENDECIES).
As we do not have appendencies we would like the topic name to fill the whole table space. This should be optional with a configurable parameter.

**Comment by vvmruder** [comment]
This will be solved on its own. The appended documents are only available in the FULL flavour. This is obsolete soon. We will not offer this since federal offices agreed this report is not necessary.

@voisardf What do you think?

**Comment by voisardf** [comment]
In the latest specifications for the static extract (1.7.2018) the full pdf extract is still an option and I'm unsure if the abolition of that flavour is well under way now. So the print template should still offer this options.

But in my opinion (and unless I'm missing something) this is very easy to implement, as we just have to put an selector based on the report type (parameter: isReduced) to choose between a TOC subreport template for the full (https://github.com/pyramidoereb/pyramid_oereb/blob/master/print/print-apps/oereb/toc.jrxml) and an other one for the reduced flavour where the full width can be used.

@jwkaltz @pfirpfel : or am I forgetting something? :)
