### ISSUE TITLE
Add tests for oereblex models

### ISSUE THREAD

**Issue by pfirpfel** [openoereb/pyramid_oereb#808]
Oereblex models are not covered by tests. This will probably need a refactoring of entire test setup, because all is currently based on the default models.

**Comment by jwkaltz** [comment]
Note that #1197 facilitates setting up pyramid_oereb with oereblex, in particular for testing and development purposes. However, that PR did not introduce an actual test suite for oereblex functionality.

**Comment by jwkaltz** [comment]
Deprecated, replaced by #1393
