### ISSUE TITLE
Broken import script for federal topics

### ISSUE THREAD

**Issue by kdeininger** [openoereb/pyramid_oereb#811]
The import script for the federal topics seems to be broken. It throws an AssertionError on `assert Config._config is not None`.

Furthermore, the values of the new multilingual attributes (`sub_theme` and `legend_at_web`) should be wrapped in dictionaries using a default language:

https://github.com/openoereb/pyramid_oereb/blob/7c6bb1b5d738ca0de4a19b83f9f184c9de81b7bf/pyramid_oereb/standard/xtf_import/public_law_restriction.py#L27

https://github.com/openoereb/pyramid_oereb/blob/7c6bb1b5d738ca0de4a19b83f9f184c9de81b7bf/pyramid_oereb/standard/xtf_import/view_service.py#L28

https://github.com/openoereb/pyramid_oereb/blob/7c6bb1b5d738ca0de4a19b83f9f184c9de81b7bf/pyramid_oereb/standard/xtf_import/legend_entry.py#L41

For example:

```python
sub_theme={
    default_language: parse_string(legend_entry, self.TAG_SUB_THEME)
}
```

The default language could be set using an additional command line argument.

**Comment by jwkaltz** [comment]
The application startup logic was changed in https://github.com/openoereb/pyramid_oereb/pull/736, maybe the point regarding "Config._config is not None" is a consequence of that?

**Comment by pfirpfel** [comment]
A fix is now available as a beta release via PyPi for testing:
`pyramid-oereb==1.4.3b0`
