### ISSUE TITLE
page numbers of restriction pages disappear in MapFish Print 3.18

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#813]
When updating from MapFish Print 3.10.8 to 3.18, the page numbers aren't printed anymore on the restriction pages.
(Reproducible on local test data set).

Work-around: stay on MapFish Print version 3.10.8 for the time being.

**Comment by pvalsecc** [comment]
I'm having a look. I guess something changed with the new version of Jasper...
