### ISSUE TITLE
Implementing rules for sorting law records in the static extract

### ISSUE THREAD

**Issue by StefanKiener** [openoereb/pyramid_oereb#818]
A sorting for the law records (documents) should be implemented (in the Mapfish Print renderer for the static extract). The following rules should be applied

- Cantonal law reoords before federal law records
- Order ascending by SAR-number (cantonal) and by SR-number (federal) within the groups of cantonal and federal law records

The attachement 'LawRecords_ExampleShowingDesiredSorting.png' shows the desired sorting put into practice in the OEREB-Client Kanton Aargau. The same behaviour should be implemented into the static extract.
![LawRecords_ExampleShowingDesiredSorting](https://user-images.githubusercontent.com/11230325/54980366-d0a23400-4fa5-11e9-9c0d-454ba59a45d2.png)

**Comment by svareg** [comment]
Hello,

At BS we have the same need and these sorting rules also suit us.
But it seems that there is no information on a document that tells us if it is federal or cantonal. 

@StefanKiener How do you know if a document is federal or cantonal ? Only with a Number-Prefix (SAR or SR) ? 

Thanks,
Guillaume.

**Comment by StefanKiener** [comment]
@svareg I guess the Number-Prefix is the only property we can use for the differentiation.
At the canton Aargau we use OEREBlex to manage the law records. In fact OEREBlex contains a property 'federal_level' with the values "Kanton" or "Bund", but this property is not part of the DATAExtract (JSON/XML) and therefore can't be used for the differentiation.

@kdeininger Hi Karsten, you implemented this rule for your OEREB-Client (based on the DATAExtract), what properties did you use?

**Comment by kdeininger** [comment]
There is no special implementation in our Client. The attached laws are just rendered in the same order as received from OEREBlex. This way, the federal documents are listed after the cantonal ones, at least in most cases. We only group documents with the same title, but this has no effect on their order.

**Comment by CoNussberger** [comment]
At canton GR the need for sorted law records has also been identified. 
As I suspect that the option "keep the sorting of OEREBlex" does not work reliably in all cases (what if two public law restrictions of the same topic do not have the same set of law records?),  I think we should try to sort by OfficialNumber. As the Numberprefix is part of this attribute at least the grouping should work this way. As the cantonal prefix is different from canton to canton I don't see a general solution to put the cantonal records bevor the federal records, without a change of the federal speification, but the sorting by number and the grouping effect would already incrase the usability. 

What do you think?

**Comment by jwkaltz** [comment]
Implemented in #925 and tested with dummy data; testing on a real installation will be done by @CoNussberger with an upcoming daily build of pyramid_oereb.
