### ISSUE TITLE
Implementing rules for grouping or sorting public law restrictions in the static extract

### ISSUE THREAD

**Issue by StefanKiener** [openoereb/pyramid_oereb#819]
A grouping or sorting for the public law restriction records (documents) should be implemented (in the Mapfish Print renderer for the static extract). The following rules should be applied
Public law restrictions with identical title should

- either be grouped to one record with multiple URL's (see attachement)
- or be sorted, so that records with identical title are listed contiguous

The attachement 'PublicLawRestrictionRecords_ExampleShowingDesiredGrouping.png' shows the desired grouping put into practice in the OEREB-Client Kanton Aargau. The same behaviour should be implemented into the static extract.
![PLRRecords_ExampleShowingDesiredGrouping](https://user-images.githubusercontent.com/11230325/54981095-c41edb00-4fa7-11e9-9a2a-048dbcb3f19b.png)

The attachement 'PLRRecords_ExampleShowingFalseSorting.png' shows the actual false sorting
![PLRRecords_ExampleShowingFalseSorting](https://user-images.githubusercontent.com/11230325/54981165-f0d2f280-4fa7-11e9-92e2-d78edf26ed3b.png)

**Comment by svareg** [comment]
Hello,

I just opened a dupplicated of this ticket here : https://github.com/openoereb/pyramid_oereb/issues/861
The other ticket can be closed I think. 

But in summary I agree with @StefanKiener here.
I would still prefer the option 1 (grouped to one record with multiple UR)

**Comment by jwkaltz** [comment]
If I remember correctly the discussion at the user group, @voisardf is going to discuss this point in the Oereb "Gremium", to see if a specification can be defined (because currently, there is nothing specified in the requirements, as far as I know)

**Comment by svareg** [comment]
OK, thank you for the information.
I didn't pay attention to this particular point during the usergroup.

**Comment by voisardf** [comment]
@jwkaltz: Yes, I already asked swisstopo, if there would be a possibility to specify sorting rules and as the specifications will undergo a new revision soon, they were quite inclined to add this point to the discussion.

But the when exactly is to be defined. So we might wan't to have a first "pyramid_oereb internal" proposition to build on that could become the new specification...

**Comment by jwkaltz** [comment]
@voisardf thanks for the info. So I guess next step is that somebody from the user group takes the lead to define the requirement? WDYT @vvmruder ?

**Comment by CoNussberger** [comment]
At the canton GR we have the same need for  grouped and sorted legal provisions. As the land use plans in GR usually have several legal provisions, we need a clearly structured solution.  In consultation with @vvmruder we would take the lead to define the requirements based on the suggestion described by @StefanKiener and to coordinate with other interested cantons (at the moment BS and AG).

**Comment by jwkaltz** [comment]
The requirement was implemented in #948 and the functionality therefore be available in all new versions (including development versions) starting today.
