### ISSUE TITLE
Question about municipalities

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#823]
Just a question: why is there a loop over all the municipalities in:

- https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/standard/sources/municipality.py
- https://github.com/openoereb/pyramid_oereb/blob/master/pyramid_oereb/lib/processor.py (lines 302ff)

Based on the real_estate-record the municipality is known to the application and needn't be determined by this loop. But there might be another reason. Who knows more about this?

**Comment by vvmruder** [comment]
Investigating... ;)

**Comment by vvmruder** [comment]
From my first perspective this looks like some design thing. We wanted to separate the layers really. So the core functionality of pyramid_oereb should not depending on what data source it is docked. But as far as I see it in the code it would be possible to go on dedicated municipality from beginning. This will save probably a lot of iterations.

@kdeininger & @voisardf : Can you please have a look too?

**Comment by kdeininger** [comment]
Yes, I think the idea was to be able to use any kind of municipality source that returns a list of municipality records. But anyway, it should be possible to pass a parameter, e.g. the `fosnr`, to get only the affected municipality and remove this iteration.

**Comment by voisardf** [comment]
Indeed, as far as I understand it, if we already know in what municipality lies the selected real estate, we do not need the iteration in the processor. - Unless there exist properties beeing part of two municipalities?

**Comment by vvmruder** [comment]
Hey folks. I offered a first promising improvement on this iteration thing. Please have a look at it #965
