### ISSUE TITLE
Mapfish Print 3.19.0 not working with oereb

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#843]
The newest release of Mapfish Print, 3.19.0, is not working with pyramid_oereb. A request for an extract print results in this error:

Error while processing request:
net.sf.jasperreports.engine.JRException: Errors were encountered when compiling report expressions class file:
1. org.apache.commons.lang.StringUtils cannot be resolved to a type
                value = org.apache.commons.lang.StringUtils.join((List<String>)((java.util.Map)parameter_TOC_Appendices.getValue()).get( ((java.lang.String)field_label.getValue())), "\n"); //$JR_EXPR_ID=10$
                        <--------------------------------->
2. org.apache.commons.lang.StringUtils cannot be resolved to a type
                value = org.apache.commons.lang.StringUtils.join((List<String>)((java.util.Map)parameter_TOC_Appendices.getValue()).get( ((java.lang.String)field_label.getOldValue())), "\n"); //$JR_EXPR_ID=10$
                        <--------------------------------->
3. org.apache.commons.lang.StringUtils cannot be resolved to a type
                value = org.apache.commons.lang.StringUtils.join((List<String>)((java.util.Map)parameter_TOC_Appendices.getValue()).get( ((java.lang.String)field_label.getValue())), "\n"); //$JR_EXPR_ID=10$
                        <--------------------------------->
3 errors
.

To reproduce:
* check out master of pyramid_oereb
* change print/Dockerfile to FROM camptocamp/mapfish_print:3.19.0
* do "make serve"
* request in the browser http://localhost:6543/oereb/extract/reduced/pdf/CH113928077734

**Comment by pvalsecc** [comment]
@jwkaltz, I LOVE your issues! The steps to reproduce are just perfect...
