### ISSUE TITLE
Update pyproj

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#869]
There are now some new versions of pyproj available. The version downgrade done in PR #810 is probably not needed anymore.

Issue depending on https://gitlab.com/gf-bl/python-reprojector/issues/2, because this project also restricts the version used.

**Comment by vvmruder** [comment]
Is this solved now?

**Comment by jwkaltz** [comment]
@vvmruder we should include this update in the scope of subproject 1 of pyramid_oereb V2

**Comment by vvmruder** [comment]
I agree.
