### ISSUE TITLE
Only uppercase GET-Parameternames?

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#870]
In v1.5.0 (and very probably also in earlier releases) all the GET-Parameters (GNSS, LANG, XY, TOPICS etc.) only work when the parameter name is transmitted in uppercase letters e.g.

not working: https://www.oereb-test.apps.be.ch/extract/reduced/json/CH413559468524?lang=fr
working: https://www.oereb-test.apps.be.ch/extract/reduced/json/CH413559468524?LANG=fr

In the Weisung "ÖREB-Webservice" all GET-parameters are in uppercase letters. So this behaviour may be compliant but it is a bit counterintuitive because the URL-path parameters are also in uppercase letters in the Weisung but they work in any case e.g.

working: https://www.oereb-test.apps.be.ch/extract/reduced/json/CH413559468524?LANG=fr
working: https://www.oereb-test.apps.be.ch/extract/REDUCED/json/CH413559468524?LANG=fr
working: https://www.oereb-test.apps.be.ch/extract/ReDuCeD/json/CH413559468524?LANG=fr

I propose to change the behaviour of pyramid_oereb in order to enable GET-Parameternames in any case (upper, lower or mixed). What do others think about that?

**Comment by svareg** [comment]
@peterschaer I agree 
I had the same problem with the LAYERs parameter:

For exemple in the file mapfish_print.py, we are looking for main_page_params['LAYERS'][0].
But is your "layers" parameter in the wms url is not uppercase, then pyramid_oereb crashes.

This may not be a top priority, but I agree, it is very counterintuitive, and this change could be a good "nice to have".

**Comment by vvmruder** [comment]
After digging really deep into RFC's of URI schema specifications I was not able to find a "standard" how the "query-part" of an URL is defined. There is simply no rule except it should be a ampersand separated list of key-value pairs connected by '=' always following after a '?' at the end of the 'path' part of URL and maybe terminated by '#' at the end.

so (the examples section):
https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

No information about case in/sensitivity. That for instance the part of the 'path' like 'REDUCED' is accepted as case insensitve element is the specified behaviour of an URI. The 'path' part is case insensitve. And therefore its handled correctly.

But I agree, it may be a bit cumbersome to have these strange case sensitive parameters in the 'query' part , so I guess we can make it case insensitive.
