### ISSUE TITLE
Version 1.5.0 : Font Cadastra ist not available by default in the templates configuration.

### ISSUE THREAD

**Issue by svareg** [openoereb/pyramid_oereb#875]
Hello,

I installed the last version of MapFishPrint because I migrate to pyramid_oereb 1.5.0.

I get the following error when I try to generate a report : 

```
Error while processing request:
net.sf.jasperreports.engine.util.JRFontNotFoundException: Font "Cadastra" is not available to the JVM. See the Javadoc for more details.
```

The file Cadastra.jar does actually not exist in the WEB-INF\lib folder by default. 
I had to copy it manually.

I think it would be good either to add it to the pyramid_oereb_mfp repository, or to add it in MFP by default.

What do you think?

Thanks,
Guillaume.

**Comment by jwkaltz** [comment]
Hi Guillaume,
actually the Cadastra is now included within MapFishPrint, which is why we do not have anymore in https://github.com/openoereb/pyramid_oereb_mfp/tree/master/print-apps/oereb

Are you sure you are printing with the upgraded MapFish-Print version?

**Comment by svareg** [comment]
Hello Wolfgang,

I downloaded the last release (war file version 3.20.1) from here : 
http://repo1.maven.org/maven2/org/mapfish/print/print-servlet/3.20.1/

And it seems that the font is not in the WEB_INF folder:

![grafik](https://user-images.githubusercontent.com/36037102/59759356-3265f780-9290-11e9-9d84-f762484eac3d.png)

**Comment by jwkaltz** [comment]
Ah, I see that Cadastra.jar is only available by default when running MapFish-Print within Docker. 
As we run tests on this basis, I did not notice this before, sorry about that.

But, I am still not sure we should add it to the repository - I feel that it makes more sense to recommend using the print project within docker (which is in fact the recommended way, even though we have not documented that yet), and to document what needs to be done if it runs outside docker (in this case: copy the Cadastra,jar to a WEB-INF/lib directory).

Any objection from you, Guillaume? Or from other people?

**Comment by svareg** [comment]
For me it will be ok this way.
I just need to know where I can find Cadastra.jar as well.

I copied it from an old version of MFP, but if I hadn't it, I would not have know where to find it.

Thanks,
Guillaume.

**Comment by jwkaltz** [comment]
That's a good point; the version MapFish-Print uses (when dockerized) is here:
https://github.com/mapfish/mapfish-print/tree/master/core/docker/usr/local/tomcat/webapps/ROOT/WEB-INF/lib

We can add this information to the documentation as well. But I will wait a couple of days to see if there are other opinions about this topic.

**Comment by voisardf** [comment]
hi, we are undockerized for now, so it would be helpful to have the documentation for both cases indeed. 👍

**Comment by pfirpfel** [comment]
I don't like the fact, that the Cadastra.jar would only be available outside this GitHub org. Can we add it either to openoereb/pyramid_oereb_mfp (since it is a jasperreports font package) or create a separate project inside the openoereb org?

I added a PR for the documentation: #877

**Comment by jwkaltz** [comment]
Hi Guillaume, the documentation about this point is now being enhanced in the pyramid_oereb_mfp project, see https://github.com/openoereb/pyramid_oereb_mfp/pull/10
