### ISSUE TITLE
Drop python 2.7 support

### ISSUE THREAD

**Issue by pfirpfel** [openoereb/pyramid_oereb#889]
Python 2.7 [stops receiving bug fixes after January 1, 2020](https://www.python.org/dev/peps/pep-0373/). By then we should drop python 2.7 support and all users should have migrated to python3 by then.

**Comment by vvmruder** [comment]
How is this done normally? I mean: We already have implemented full Python3 support. Do we just remove all Python2 stuff?

**Comment by pfirpfel** [comment]
More and more libraries will stop supporting python 2.7, meaning there will be no more updates for it. Some already dropped support, like numpy. So we would be stuck on old, possibly insecure versions of dependencies.

To drop support ourselves, we just have to define a last version that supports 2.7. All newer ones remove the python 2 code and configurations from stuff like travis. And we can also update dependencies again.
