### ISSUE TITLE
LengthShare and NrOfPoint in wrong XML namespace

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#891]
I validated one of our XML extract (based on pyramid_oereb 1.5.0) in XMLSpy:

[CH743546874207.zip](https://github.com/openoereb/pyramid_oereb/files/3451649/CH743546874207.zip) or https://www.oereb-test.apps.be.ch/extract/reduced/xml/CH743546874207

XMLSpy complains about LenghtShare not being allowed at this location. It suggests to rename <LengthShare> to <data:LengthShare> The same is valid for NrOfPoints.

Therefore I think that in #854 the elemens LengthShare and NrOfPoints were moved to the right place but the correct namespace was not inserted. That should be corrected in order to get a valid xml extract.

**Comment by pfirpfel** [comment]
Already fixed with #872
