### ISSUE TITLE
OEREBLex category "Bezirke" brings error in geolink_formatter

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb#903]
Hi everyone

Kanon AI has set their OEREBLex documents in the subcategory "Bezirk", which is not supported from the geolink_formatter.

pyramid_oereb shows the error message:
"XMLSyntaxError: Element 'document', attribute 'federal_level': [facet 'enumeration'] The value 'Bezirk' is not an element of the set {'Gemeinde', 'Kanton', 'Interkantonal', 'Bund'}. (line 0)"

Is the strucutre for the geolink_formatter fixed, or could that be addapted? 
I currently manually add the Bezirk in the xsd for now. 

Thanks
Max

**Comment by jwkaltz** [comment]
I guess this originates here: https://github.com/openoereb/geolink_formatter/blob/9414821571f43a2987eedd6cdc71a5da801e6f88/geolink_formatter/schema/v1.1.1.xsd#L40

What do you think @kdeininger , should the schema be extended?

**Comment by kdeininger** [comment]
Is this an official modification by Sitrox? If a new version of the geoLink schema has been released, we should add the new version, but I have no information about a new schema release. Otherwise, it should be safe to add the new enumeration value in the existing schema, as it does not break backward compatibility.

**Comment by MaxHoeferGEOINFO** [comment]
Hi everyone, 

thanks so far, I contacted Sitrox for a statement if that is an official change.
Cheers
Max

**Comment by KTAI-GIS** [comment]
Hi everyone,
The Name of "Gemeinde" in Canton Appenzell Innerrhoden is "Bezirk". It's not a Problem to work with the Name "Gemeinde" internally but in the interface it should appear as "Bezirk".
Kind regards
Pascal

**Comment by tschoppi** [comment]
Hi all,

The Canton Appenzell Innerrhoden is a special case, as mentioned in the previous comment, in that the label for the lowest federal level “Gemeinde” is actually “Bezirk”. This was accommodated with a manual override of the label and has thus not made it into the GEO-Link XML schema specification.

In principle it should suffice to add a new enumeration value in the schema. If you want to be really strict about it, the values “Gemeinde” and “Bezirk” of `federal_level` are mutually exclusive and only one of them should be used by a given instance of OEREBlex. That is currently the case.

I hope this helps.

Best regards,
Jan

**Comment by kdeininger** [comment]
I have released a new version of [geolink_formatter](https://pypi.org/project/geolink-formatter/) with a fix for this issue. It should be available with the next dependency update.

**Comment by jwkaltz** [comment]
As indicated in https://github.com/openoereb/pyramid_oereb/issues/903#issuecomment-549372672, issue should be fixed - closing issue.
