### ISSUE TITLE
Windows incompatibility for numpy 1.16.4

### ISSUE THREAD

**Issue by voisardf** [openoereb/pyramid_oereb#906]
On Windows, the version 1.16.4 of numpy which is used for pyramid_oereb v1.5.1 get's Apache 2.4.34 blocked for whatever reason...

Version 1.16.3 is fine.

not sure if a intervention ist needed. We dealt with the issue locally by downgrading the version in the pyramid_oereb 1.5.1 egg

**Comment by jwkaltz** [comment]
Thanks for the info @voisardf !

**Comment by jwkaltz** [comment]
@voisardf Have you tried version 1.16.5, does it block Apache (on Windows) too?

**Comment by voisardf** [comment]
unfortunately, it looks like 1.16.5 has the same issue...
Maybe the 1.17.2 is better - I would have to check.

**Comment by jwkaltz** [comment]
FYI, it sounds similar to this issue: https://github.com/numpy/numpy/issues/8559
You could try a different Apache configuration as suggested there, to see if that helps.

**Comment by voisardf** [comment]
for information: I also found out yesterday that this version of numpy is also responsible for an infinite loop when creating our canton specific pdf extract.

**Comment by voisardf** [comment]
Just found out that the version 1.16.6 of numpy also creates issues on windows with pyramid_oereb_mfp. Took me half a day due to a less than specific error message in Tomcat.
[tomcat9-stdout.2020-05-13.log](https://github.com/openoereb/pyramid_oereb/files/4623297/tomcat9-stdout.2020-05-13.log)

**Comment by jwkaltz** [comment]
> Just found out that the version 1.16.6 of numpy also creates issues on windows with pyramid_oereb_mfp (happend with v.1.7.x). Took me half a day due to a less than specific error message in Tomcat.
> [tomcat9-stdout.2020-05-13.log](https://github.com/openoereb/pyramid_oereb/files/4623297/tomcat9-stdout.2020-05-13.log)

@voisardf I am not sure this is related to numpy?

**Comment by voisardf** [comment]
Quite sure. Because I just changed that version and now it's working. Locally and on the dev server. But it might be related to a dependency of numpy, if there are any? It is really hard to trace back, because there are now clear error messages.

I checked with print-servlet version 3.20.3 and 3.22 both work with numpy 1.16.3.

Other than that I use all the pyramid_oereb requirements except zope.sqlalchemy==1.1 to insure compatibility with sqlahelper 1.0 we still use in the parent pyramid project (we are planning to get rid of sqlahelper until the end of the month).

I didn't try the apache configuration yet you suggested: https://github.com/numpy/numpy/issues/8559
I might have a look into that.

**Comment by jwkaltz** [comment]
But the print application in MFP is separate from pyramid_oereb, and does not use python. So if you see a difference in behavior in MFP depending on which version of numpy you use in pyramid_oereb, then its means that the extract data in pyramid_oereb must be different depending on the version of numpy? Or am I misunderstanding your report completely?

**Comment by voisardf** [comment]
we found out that on windows, numpy tries to access a dll outside the venv, thus, if you have different versions of numpy installed (different pyramid projects) they will block each other and give unrelated error messages.

It seems that numpy 1.16.6 on it's own  works ok.

**Comment by jwkaltz** [comment]
So, we can close the issue and remove the line https://github.com/openoereb/pyramid_oereb/blob/20652e3fb1dc1f7dbd9e4a39f1787811c5dc91d5/requirements-windows.txt#L2 ?

**Comment by voisardf** [comment]
I do not know what the good answer is... Probably yes. - I think only SH and we are on windows and both aware of the fact that numpy causes problems if you have projects with different versions on the same server.
We just have to keep that in mind if ever an other canton with windows joins the group.

**Comment by jwkaltz** [comment]
@voisardf FYI as the new versions of pyramid_oereb will work only with Python3, we can now upgrade numpy in pyramid_oereb to the newest version (which only works with Python3). I will close this issue here, please open a new one if the newest version of numpy (currently: 1.19.0) also has issues on Windows.
