### ISSUE TITLE
Links to Symbols: ".png" missing

### ISSUE THREAD

**Issue by zigertiger** [openoereb/pyramid_oereb#908]
Legend Symbols are provided as PNG files (i.e. stored as Base64 images in the DB). However, any file name extension (`.png`) is missing in Xml extracts wich is an error IMHO.

Example:
`
<data:SymbolRef>
http%3A%2F%2Fiap-map.gl.ch%2Foereb%2Fwsgi%2Foereb%2Fimage%2Fsymbol%2FLandUsePlans%2F3%2F1632.71-01-01
</data:SymbolRef>
`

fix:
`
<data:SymbolRef>
http%3A%2F%2Fiap-map.gl.ch%2Foereb%2Fwsgi%2Foereb%2Fimage%2Fsymbol%2FLandUsePlans%2F3%2F1632.71-01-01.png
</data:SymbolRef>
`

**Comment by vvmruder** [comment]
This is due to the problem that file type is not necessarily png. It also can be another. We can try to obtain the type by the data of the file. But this is not 100% save.

**Comment by kdeininger** [comment]
I will give it a try using the [filetype](https://pypi.org/project/filetype/) library.
