### ISSUE TITLE
Ampersand not escaped in XML extract

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#911]
We have a few public law restrictions with an ampersand (&) in the information attribute. in my opinion the ampersand should be escaped by pyramid_oereb (with `&amp;`). This does not happen, therefore we have invalid xml output in these cases. e.g.
https://www.oereb.apps.be.ch/extract/reduced/xml/CH313516468953

**Comment by svareg** [comment]
Hi there,

May I ask what the status of this issue is ?

I have the same problem, but with the columns **type_code** and **type_code_list** on table **LegendEntry** and **PublicLawRestriction**, which contain **&** and which are not escaped in XML extracts.

Thanks!

**Comment by vvmruder** [comment]
Issue is closed already due to its solution. May I politely ask you to open a new one with your request? :)
