### ISSUE TITLE
Central proxy configuration not used in oereblex integration

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#922]
The pyramid_oereb standard configuration mentions a central proxy configuration: 
https://github.com/openoereb/pyramid_oereb/blob/1a9ccf61932083696f9ac44fed85ddac1c37d0af/pyramid_oereb/standard/pyramid_oereb.yml.mako#L9

However, this proxy setting is not used in the oereblex integration. Oereblex integration needs a specific proxy configuration: https://github.com/openoereb/pyramid_oereb/blob/1a9ccf61932083696f9ac44fed85ddac1c37d0af/pyramid_oereb/standard/pyramid_oereb.yml.mako#L144

In my opinion, oereblex integration should use the central proxy configuration, and not provide an additional configuration for a proxy.

**Comment by kdeininger** [comment]
Improve doc of configuration.

**Comment by vvmruder** [comment]
@kdeininger & @jwkaltz What is the status? Is this in the "wont fix" state?

**Comment by vvmruder** [comment]
@kdeininger & @jwkaltz What is the status? Is this in the "wont fix" state?
