### ISSUE TITLE
Integration of OEREBLex not multilingual

### ISSUE THREAD

**Issue by CoNussberger** [openoereb/pyramid_oereb#923]
In the canton GR OEREBLex Supports multilingual calls in teh following form:

https://oereb-gr-preview.000.ch/api/geolinks/154.xml?locale=de
https://oereb-gr-preview.000.ch/api/geolinks/154.xml?locale=it
https://oereb-gr-preview.000.ch/api/geolinks/154.xml?locale=rm

The multilingual call of OEREBLex is not supported by pyramid_oereb. In the pyramid_oereb_standard.yml just one language can be defined for OEREBLex.

**Comment by kdeininger** [comment]
This has to be implemented in the `OEREBlexSource`. Maybe the `geolink_formatter` lib has to be modified too.

**Comment by kdeininger** [comment]
There are no changes to the `geolink_formatter` lib needed. It should be sufficient to modify the `OEREBlexSource`:

https://github.com/openoereb/pyramid_oereb/blob/8d047e63ff02f7bb625ffede6a318f8069bd37cd/pyramid_oereb/contrib/sources/document.py#L84

On this line, the URL parameter has to be added.

```python
documents = self._parser.from_url(url, {'locale': self._language}, proxies=self._proxies, auth=self._auth)
```

**Comment by CoNussberger** [comment]
I' am not 100% shure, but i think this is not sufficient, because the configuration in the yml file just allows to set one language for the OEREBLex response. 
See pyramid_oereb.yml.mako line 132

This value is also checked in pyramid_oereb/contrib/sources/document.py line 95 and 60. There it has to be a two caracter language specification.

**Comment by kdeininger** [comment]
Sorry, I just had a short look at the code. In this case, we have to add an additional argument to the `read` method to pass a dynamic language value per request.

https://github.com/openoereb/pyramid_oereb/blob/8d047e63ff02f7bb625ffede6a318f8069bd37cd/pyramid_oereb/contrib/sources/document.py#L68

The configured language can be used as default value, if no language has been specified on `read`.

**Comment by kdeininger** [comment]
I had a deeper look at the code. It should be possible to pass the language parameter from the extract reader through the `DatabaseOEREBlexSource`, but the behavior might be a bit tricky.

I suppose, that you can define a default language at `OEREBlex`. If a document is requested with a language, that is not available, the default language is used as fallback, as it is also implemented in `pyramid_oereb`. Unfortunately, the language is not returned with the document element in the geoLink response. That is why you cannot determine, if the document is returned in the requested language or the default one. For example, if the default language is German and you requests the documents in French, you have to expect the documents to be in French, even if some might be in German (by default). This behavior could result in wrong language keys in the XML and JSON extracts.

**Comment by kdeininger** [comment]
It could be useful to pass the `Parameter` object from the request to all readers and sources in more generic way.  Otherwise, we would have to implement a special handling just for the `OEREBlex` sources.

@vvmruder, @jwkaltz, @pfirpfel: What do you think?

**Comment by jwkaltz** [comment]
> It could be useful to pass the `Parameter` object from the request to all readers and sources in more generic way. Otherwise, we would have to implement a special handling just for the `OEREBlex` sources.
> 
> @vvmruder, @jwkaltz, @pfirpfel: What do you think?

Makes sense to me.

**Comment by vvmruder** [comment]
I think this would be a good idea. But we also should address the company behind OEREBlex to maybe update their API behaviour. Because the described situation will end in not satisfying output of documents.

**Comment by kdeininger** [comment]
@tschoppi, is it possible to extend the geoLink schema with a language attribute for the document element? This new attribute should contain the language of the returned document.

For example:
```xml
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="geolinks">
        <xs:complexType>
            <xs:choice minOccurs="1" maxOccurs="unbounded">
                <xs:element name="document">
                    <xs:complexType>
                        ...
                        <xs:attribute name="language">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="de"/>
                                    <xs:enumeration value="fr"/>
                                    <xs:enumeration value="it"/>
                                    <xs:enumeration value="rm"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        ...
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
</xs:schema>
```

**Comment by tschoppi** [comment]
It is possible to add this additional metadatum to the GEO-Link XML response, although it involves some data wrangling. We will schedule this for the next API update.
