### ISSUE TITLE
Encoding of & in XML Extract

### ISSUE THREAD

**Issue by svareg** [openoereb/pyramid_oereb#926]
The presence of the character **&** in the columns **type_code** or **type_code_list** on table **LegendEntry** and **PublicLawRestriction** prevents the creation of a valid XML-Extract.

This character should be encoded as **&amp;** in the whole XML-Extract.

Thanks.

**Comment by CoNussberger** [comment]
Just as supplementary information: We have the same problem with & used in the "name" attribute of the "office" table.

**Comment by vvmruder** [comment]
I pushed changes to #939. Could you check in a test environment if it solves your issues?
