### ISSUE TITLE
Hook method for LogoRef Urls

### ISSUE THREAD

**Issue by svareg** [openoereb/pyramid_oereb#929]
Hello,

When we generate a xml or json extract, the hook method *get_symbol_ref()* is called. The configuration allow us to overwrite this method with our own, so that we can control which URL are used and published in the extract. This is very cool, because it allows us to set "extern" urls in extract, while using "intern" urls in our code (because we have sometimes complex proxies configuration)

Unfortunately, this does not work for the following attributes :

- LogoPLRCadastreRef
- FederalLogoRef
- CantonalLogoRef
- MunicipalityLogoRef

In the code, a simple *self._request.route_url()* is called.
The consequences for us is that the published urls are using internal IP adresses.

![grafik](https://user-images.githubusercontent.com/36037102/67759455-bcdd1580-fa3f-11e9-9e73-f5d600851872.png)

Could it be possible to have the same behaviour here, with an overwritable hook method *get_logo_ref()* instead of a simple *route_url()* call ?

What do you think ?
Thanks!

**Comment by lopo977** [comment]
Overwritable hook method get_logo_ref() could be a nice feature.
Please we are still using the reference implementation. (Tessin)
Keep attention in implementing dynamic binding to a new overridable implementation via configuration (strategy pattern).
Thank you.

**Comment by peterschaer** [comment]
We would also welcome this feature and would also be willing to contribute in some way.

**Comment by jwkaltz** [comment]
@svamaa this can be closed as per #1744, right?
