### ISSUE TITLE
gather usage information of pyramid_oereb

### ISSUE THREAD

**Issue by jwkaltz** [openoereb/pyramid_oereb#936]
pyramid_oereb shall be extended to gather usage information within pyramid_oereb
itself. The data gathered will be persisted in the database configured for the instance of
pyramid_oereb, allowing the operator or owner of the application to query at any time
the usage statistics for that database.

**Comment by danduk82** [comment]
Please find the proposed solution in [this PR](https://github.com/openoereb/pyramid_oereb/pull/961)

**Comment by jwkaltz** [comment]
Implemented in #987
