### ISSUE TITLE
Too many legend items in other legend in PDF extract

### ISSUE THREAD

**Issue by CoNussberger** [openoereb/pyramid_oereb#944]
The BBOX used for the WMS-request stored in the json extract returns a larger image than shown in the PDF-extract. In some cases this leads to too many legned itms in other legend in the PDF-extract.

The following example illustrates the issue quite well:

[20191114113524_extract.pdf](https://github.com/openoereb/pyramid_oereb/files/3846802/20191114113524_extract.pdf)

[CH197477539179json.txt](https://github.com/openoereb/pyramid_oereb/files/3846808/CH197477539179json.txt)

As the WMS is not accessible from the internet here the resulting images requested from the wms:

![grundbuchplan_oereb](https://user-images.githubusercontent.com/23398143/68863536-da70d700-06ef-11ea-8a04-d8d894780a9a.png)
![nutzungsplanung_oereb](https://user-images.githubusercontent.com/23398143/68863540-dcd33100-06ef-11ea-8cf7-c6bf4d00fd16.png)

**Comment by voisardf** [comment]
I can confirm this behaviour. I think it's somewhere related to the percentage set in the margin parameter around the real estate. We will have to dig a little bit deeper to tell exactly where it comes from.

**Comment by peterschaer** [comment]
You have to tweak the settings a little bit. We have the following values:

**in config.yaml (pyramid_oereb_mfp):**

- minMargin: 42

**in pyramid_oereb_standard.yml:**

- buffer: 30

With those values both BBOX are almost identical.

**Comment by voisardf** [comment]
@jwkaltz @marionb @vvmruder : So shouldn't we set the default values of the config so they extracts are as perfectely identical as possible?

**Comment by CoNussberger** [comment]
For me it works with the values given py @peterschaer and I think this issue can be closed as the default values in the repos are set at minMargin=10 and buffer=10. This is quite a narrow buffer but as far as I saw sould work as well.
For our case I use buffer 30 and minMargin: 42 looks better to me (and I like it that the solution to my problem is 42 :-) )
