### ISSUE TITLE
ÖREBLex development - new document type "notice" for "weitere Informationen und Hinweise"

### ISSUE THREAD

**Issue by MaxHoeferGEOINFO** [openoereb/pyramid_oereb#959]
Hello 

Sitrox will be releasing a new version of their OEREBLex which will include a new document type "notice" for "weitere Informationen und Hinweise". 

The documents stored in this category should then be pulled from pyramid_oereb in the section "Weitere Informationen und Hinweise", similarly as "Gesetzliche Grundlagen" are pulled and displayed right now.

Furthermore, it is requested from the canton AI, that it's sufficient for an geometry to then have either a geolink which refers to the "Gesetzliche Grundlagen" or a link to the "Weitere Informationen und Hinweise". 

There is an issue for the adaption of the geolink_formatter already here. https://github.com/openoereb/geolink_formatter/pull/63

Thanks & Regards,
Max

**Comment by KTAI-GIS** [comment]
Explanatory I would like to add a comment that there are topics with only notices, for example "Kataster belastete Standorte" with a disclaimer and topics with legal documents and notices as well. All the documents use the same geolink from ÖREBlex per element.

**Comment by ger-benjamin** [comment]
Tested and fixed by #1010
