### ISSUE TITLE
Poor performance for OEREBlex queries

### ISSUE THREAD

**Issue by vvmruder** [openoereb/pyramid_oereb#992]
It was reported that OEREBlex API calls are slow. This means that time from request to response lasts regularly more then 5 seconds which is indeed not satisfying.

@MaxHoeferGEOINFO & @jwkaltz could you please add some details of your statistics here?

**Comment by jwkaltz** [comment]
Regarding statistics, what I have so far is this:
[oereb_cache_perfs_results (1).xlsx](https://github.com/openoereb/pyramid_oereb/files/4107778/oereb_cache_perfs_results.1.xlsx), here a high-level summary:
* of 99 test extracts in Schwyz (which uses Oereblex), 49 extracts take more than 4 seconds
* of these extracts (the ones taking more than 4 seconds), the average time is 6.5 seconds
* with "full cache" approach like discussed in PR#984, the average time of these extracts drops from 6.5 seconds to 3 seconds
* with a "extract local cache" as suggested in PR#993, I do not have any numbers yet, but if it is ok with @ralphschulerSZ , we can do a benchmark for that approach next week.
