### ISSUE TITLE
shapely install on windows (again)

### ISSUE THREAD

**Issue by peterschaer** [openoereb/pyramid_oereb#999]
With v1.7.0 the installation on windows has become hard again. Like in #585 the problem is with shapely. v1.7.0 requires `shapely==1.6.4.post1`. There are no binary wheels for Windows for Shapely 1.6.4.post1 on [PyPI](https://pypi.org/simple/shapely/). I was able to find a binary wheel on a [separate site](https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely) but only for `shapely==1.6.4.post2` Therefore I had to tweak the requirements.txt in the same way as is described in #585. Would it be possible to provide up to date wheels for windows in order to facilitate the installation process? Or is there another solution?

**Comment by jwkaltz** [comment]
@voisardf @svareg what do you think?

**Comment by peterschaer** [comment]
An update to Shapely 1.7.0 would be nice as it has wheels for a lot of platforms (Linux, MacOS, Windows):
https://pypi.org/project/Shapely/1.7.0/#files
But I'm unable to estimate the implications of this.

**Comment by svareg** [comment]
Hello,

I agree with @peterschaer : the best way would be an update to shapely 1.7.0 if it's possible.

The Problem with 1.6.4.post1 and 1.6.4.post2 available on https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely is that they are only available for python 3.4 and 3.5, which are almost EOL.

**Comment by voisardf** [comment]
hi all,
I also agree, if we could use 1.7.0 that would simplify a lot. Any know issues with this version?
thanks
